const state = window.__PARLAYPING_BUILDER__ || {};
const slip = state.slip || { legs: [] };
const legs = Array.isArray(slip.legs) ? slip.legs : [];
const parlayPanel = document.querySelector('.parlay-panel');
const picks = document.getElementById('picks');
const tuneBtn = document.getElementById('tuneBtn');
const saveBtn = document.getElementById('saveBtn');
const clearAllBtn = document.getElementById('clearAllBtn');
const addPickBtn = document.getElementById('addPickBtn');
const legCount = document.getElementById('legCount');
const combinedOdds = document.getElementById('combinedOdds');
const impliedProbability = document.getElementById('impliedProbability');
const selectedBookLabel = document.getElementById('selectedBookLabel');
const openBookBtn = document.getElementById('openBookBtn');
const toast = document.getElementById('toast');
let toastTimer;

const extraStyle = document.createElement('style');
extraStyle.textContent = '.player-fallback{display:grid!important;place-items:center;font-weight:900;color:#d9f5ff}.team-text-logo{width:31px;height:31px;border-radius:50%;display:grid;place-items:center;background:#0c2940;border:1px solid #24516b;color:#b8d5e3;font-size:8px;font-weight:900}.alt-option:disabled{opacity:.28;cursor:not-allowed}.book-card.unavailable{opacity:.65}.truth-note{color:#7698ad;font-size:10px;margin-top:8px}.similar-row button:disabled{opacity:.35;cursor:not-allowed}';
document.head.appendChild(extraStyle);

function esc(value){return String(value ?? '').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function say(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700);}
function fmtOdds(value){const n=Number(value);if(!Number.isFinite(n))return '—';return n>0?`+${Math.round(n)}`:`${Math.round(n)}`;}
function impliedFromAmerican(value){const n=Number(value);if(!Number.isFinite(n)||n===0)return null;return n>0?100/(n+100):(-n)/((-n)+100);}
function initials(name){return String(name||'?').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'?';}
function marketText(leg){if(leg.displayMarket)return String(leg.displayMarket);const market=String(leg.market||'Prop');if(/atd|anytime.*touchdown/i.test(market))return 'Anytime TD Scorer';if(leg.side&&leg.line!=null)return `${String(leg.side).replace(/^./,c=>c.toUpperCase())} ${leg.line} ${market}`;return market;}
function matchupText(leg){return String(leg.matchup||leg.team||`${leg.sport||'Sport'} matchup`);}
function statusProbability(leg){const status=String(leg.status||'PENDING').toUpperCase();if(['HIT','MISS','PUSH','VOID','UNRESOLVED'].includes(status))return {label:status,value:null};if(status==='LIVE'&&Number.isFinite(Number(leg.liveProbability)))return {label:`${(Number(leg.liveProbability)*100).toFixed(1)}%`,value:Number(leg.liveProbability)*100};if(status==='LIVE'&&Number.isFinite(Number(leg.pregameProbability)))return {label:`PG ${(Number(leg.pregameProbability)*100).toFixed(1)}%`,value:Number(leg.pregameProbability)*100};if(Number.isFinite(Number(leg.pregameProbability)))return {label:`${(Number(leg.pregameProbability)*100).toFixed(1)}%`,value:Number(leg.pregameProbability)*100};return {label:'—',value:0};}
function formatStart(value){if(!value)return {date:'',time:''};const d=new Date(value);if(Number.isNaN(d.getTime()))return {date:'',time:''};return {date:d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}),time:d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})};}
function teamBadge(leg){if(leg.teamLogoUrl)return `<img src="${esc(leg.teamLogoUrl)}" alt="${esc(leg.team||'Team')}"/>`;return `<span class="team-text-logo">${esc(String(leg.team||leg.sport||'?').slice(0,3).toUpperCase())}</span>`;}
function playerPhoto(leg){if(leg.playerImageUrl)return `<img class="player-photo" src="${esc(leg.playerImageUrl)}" alt="${esc(leg.player||'Player')}"/>`;return `<span class="player-photo player-fallback">${esc(initials(leg.player))}</span>`;}
function altMarkup(leg){const currentLine=leg.line!=null?String(leg.line):'Current';const options=Array.isArray(leg.altLines)&&leg.altLines.length?leg.altLines.slice(0,5):[{line:currentLine,oddsAmerican:leg.oddsAmerican,probability:leg.pregameProbability,current:true}];const buttons=options.map((option,i)=>{const p=Number(option.probability);return `<button class="alt-option ${i===0?'selected':''}" type="button" data-line="${esc(option.line)}" data-prob="${Number.isFinite(p)?p:''}" data-odds="${esc(option.oddsAmerican??'')}" ${options.length===1&&i>0?'disabled':''}>${esc(option.line)}</button>`;});while(buttons.length<5)buttons.push('<button class="alt-option" type="button" disabled>—</button>');return buttons.join('');}
function renderLeg(leg,index){const prob=statusProbability(leg);const meter=Math.max(0,Math.min(100,Number(prob.value)||0));const start=formatStart(leg.startTimeUTC);const match=matchupText(leg);return `<article class="pick-card" data-pick="${esc(leg.id||`leg-${index+1}`)}"><header class="game-bar"><div class="team-pair">${teamBadge(leg)}</div><strong>${esc(match)}</strong>${start.date?`<span>${esc(start.date)}</span><i>•</i><span>${esc(start.time)}</span>`:''}</header><div class="pick-main"><div class="player-block">${playerPhoto(leg)}<div class="player-copy"><strong>${esc(leg.player||'Selection')}</strong><span>${esc(marketText(leg))}</span><small>${esc(match)}</small></div></div><div class="probability-meter"><span class="meter-track"><i style="--meter:${meter}%"></i></span><strong class="pick-probability">${esc(prob.label)}</strong></div><div class="pick-odds">${esc(fmtOdds(leg.oddsAmerican))}</div><button class="kebab" type="button" aria-label="Bet options">⋮</button></div><div class="alt-lines" aria-hidden="true"><div class="alt-title">Alt Lines <span class="info-dot">i</span></div><div class="alt-options" role="group" aria-label="${esc(leg.player||'Player')} alternate lines">${altMarkup(leg)}</div></div></article>`;}

function renderSlip(){if(picks)picks.innerHTML=legs.map(renderLeg).join('')||'<div class="empty-state"><strong>No legs available.</strong><p>This signed betslip does not contain any valid selections.</p></div>';if(legCount)legCount.textContent=String(legs.length);if(combinedOdds)combinedOdds.textContent=slip.combinedOddsVerified?fmtOdds(slip.combinedOddsAmerican):'—';if(impliedProbability){const p=slip.combinedOddsVerified?impliedFromAmerican(slip.combinedOddsAmerican):null;impliedProbability.textContent=p!=null?`${(p*100).toFixed(1)}%`:'—';}bindDynamic();renderTruthPanels();selectInitialBook();}
function setTuneState(open){parlayPanel?.classList.toggle('tune-open',open);tuneBtn?.classList.toggle('active',open);tuneBtn?.setAttribute('aria-expanded',String(open));document.querySelectorAll('.alt-lines').forEach(el=>el.setAttribute('aria-hidden',String(!open)));}
function bindDynamic(){document.querySelectorAll('.kebab').forEach(btn=>btn.addEventListener('click',()=>say('Bet options are ready for the next builder action.')));document.querySelectorAll('.alt-option:not(:disabled)').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.pick-card');card?.querySelectorAll('.alt-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const p=Number(btn.dataset.prob);const odds=btn.dataset.odds;const meter=card?.querySelector('.meter-track i');const label=card?.querySelector('.pick-probability');const price=card?.querySelector('.pick-odds');if(Number.isFinite(p)&&p>=0&&p<=1){if(label)label.textContent=`${(p*100).toFixed(1)}%`;if(meter)meter.style.setProperty('--meter',`${p*100}%`);}if(odds&&price)price.textContent=fmtOdds(odds);if(combinedOdds)combinedOdds.textContent='CUSTOM';if(impliedProbability)impliedProbability.textContent='Repricing';say(`${card?.querySelector('.player-copy strong')?.textContent||'Pick'} moved to ${btn.dataset.line}`);}));}
function renderTruthPanels(){const similar=document.querySelector('.similar-list');if(similar){const names=legs.slice(0,3).map(l=>l.player).filter(Boolean).join(', ');similar.innerHTML=[['Community matches',names||'This betslip','Not yet tracked'],['Alt-line comparisons','Verified alternate markets only','Awaiting data'],['Same-slate builds',`${new Set(legs.map(l=>l.gameId||l.matchup).filter(Boolean)).size||legs.length} games represented`,'Awaiting data']].map(([a,b,c])=>`<div class="similar-row"><div class="mini-avatars"></div><div><strong>${esc(a)}</strong><small>${esc(b)}</small></div><span class="tails">${esc(c)}</span><button type="button" disabled aria-label="Unavailable">＋</button></div>`).join('');}const list=document.querySelector('.insights-list');if(list){const games=new Set(legs.map(l=>l.gameId||l.matchup).filter(Boolean)).size;const live=legs.filter(l=>String(l.status).toUpperCase()==='LIVE').length;const facts=[`${legs.length} signed leg${legs.length===1?'':'s'} loaded`,`${games||legs.length} game${(games||legs.length)===1?'':'s'} represented`,slip.combinedOddsVerified?'Verified combined parlay price supplied':'Combined parlay price was not supplied',live?`${live} live leg${live===1?'':'s'} currently tracked`:'No live legs currently reported'];list.innerHTML=facts.map(x=>`<li><span>✓</span> ${esc(x)}</li>`).join('');}}
function selectInitialBook(){const preferred=String(slip.sportsbook||legs.find(l=>l.sportsbook)?.sportsbook||'DraftKings').toLowerCase();let selected=null;document.querySelectorAll('.book-card').forEach(card=>{const hit=String(card.dataset.book||'').toLowerCase()===preferred;card.classList.toggle('active',hit);if(hit)selected=card;});if(!selected){selected=document.querySelector('.book-card[data-book="DraftKings"]');selected?.classList.add('active');}if(selectedBookLabel)selectedBookLabel.textContent=selected?.dataset.book||'DraftKings';}
function verifiedBookLink(book){const matching=legs.filter(l=>String(l.sportsbook||'').toLowerCase()===String(book||'').toLowerCase());if(matching.length!==legs.length||!matching.length)return null;const links=[...new Set(matching.map(l=>l.sportsbookLink).filter(Boolean))];return links.length===1?links[0]:null;}

renderSlip();setTuneState(false);
tuneBtn?.addEventListener('click',()=>{const open=!parlayPanel?.classList.contains('tune-open');setTuneState(open);say(open?'Parlay Tune opened.':'Parlay Tune closed.');});
saveBtn?.addEventListener('click',()=>{try{localStorage.setItem(`parlayping_builder_${state.token||'shared'}`,JSON.stringify({savedAt:Date.now(),url:state.builderUrl}));saveBtn.classList.add('saved');saveBtn.innerHTML='<span>✓</span> Saved';say('Parlay saved on this device.');}catch{say('Unable to save in this browser.');}});
clearAllBtn?.addEventListener('click',()=>{if(picks)picks.innerHTML='<div class="empty-state"><strong>Your parlay is clear.</strong><p>Reload the shared link to restore the signed picks.</p></div>';if(legCount)legCount.textContent='0';if(combinedOdds)combinedOdds.textContent='—';if(impliedProbability)impliedProbability.textContent='—';say('Parlay cleared locally.');});
addPickBtn?.addEventListener('click',()=>say('Add Pick search is the next builder connection.'));
document.querySelectorAll('.book-card').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.book-card').forEach(card=>card.classList.remove('active'));button.classList.add('active');if(selectedBookLabel)selectedBookLabel.textContent=button.dataset.book==='More Books'?'Your Sportsbook':button.dataset.book;}));
openBookBtn?.addEventListener('click',()=>{const book=document.querySelector('.book-card.active')?.dataset.book||'DraftKings';const url=verifiedBookLink(book);if(url){window.open(url,'_blank','noopener,noreferrer');return;}say(`${book}: no verified full-betslip link is available for this shared parlay.`);});
async function copyLink(){const url=state.builderUrl||location.href;try{await navigator.clipboard.writeText(url);say('Betslip link copied.');}catch{prompt('Copy this link',url);}}
async function nativeShare(){const url=state.builderUrl||location.href;if(navigator.share){try{await navigator.share({title:'My ParlayPing Betslip',text:'Check out my ParlayPing betslip',url});return;}catch(error){if(error?.name==='AbortError')return;}}await copyLink();}
document.getElementById('copyLinkBtn')?.addEventListener('click',copyLink);document.getElementById('messageBtn')?.addEventListener('click',nativeShare);document.getElementById('moreShareBtn')?.addEventListener('click',nativeShare);const shareX=document.getElementById('shareXBtn');if(shareX)shareX.href=`https://x.com/intent/post?text=${encodeURIComponent('Check out my ParlayPing betslip')}&url=${encodeURIComponent(state.builderUrl||location.href)}`;
document.getElementById('analysisBtn')?.addEventListener('click',()=>say('Full analysis will only show verified research and live data.'));document.querySelector('.search-button')?.addEventListener('click',()=>say('Search is being connected to player and market discovery.'));document.querySelector('.notification-button')?.addEventListener('click',()=>say('Notifications are being connected.'));document.querySelector('.edit-title')?.addEventListener('click',()=>say('Parlay naming is being connected for saved builds.'));
