(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SESSION_KEY='parlayping_supabase_session_v1';
  let resultsByBuilder=new Map();
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
  function normUrl(value){try{return new URL(String(value||''),location.origin).href;}catch{return String(value||'');}}
  async function getUser(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return null;return r.json();}
  async function getBadge(userId,token){const r=await fetch(`${SUPABASE_URL}/rest/v1/member_badges?user_id=eq.${encodeURIComponent(userId)}&select=referral_code,founding_number,invite_count,verified_submission_count,settled_submission_count,win_count,loss_count,push_count,void_count&limit=1`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return null;const rows=await r.json();return Array.isArray(rows)?rows[0]||null:null;}
  async function getResults(userId,token){const r=await fetch(`${SUPABASE_URL}/rest/v1/community_public_posts?user_id=eq.${encodeURIComponent(userId)}&verified_pregame=eq.true&select=id,builder_url,result_status,result_summary,graded_at&order=created_at.desc&limit=100`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return[];const rows=await r.json();return Array.isArray(rows)?rows:[];}
  function referralUrl(code){return `${location.origin}/join?ref=${encodeURIComponent(code)}`;}
  function recordStats(badge){const w=Number(badge?.win_count)||0,l=Number(badge?.loss_count)||0,p=Number(badge?.push_count)||0,v=Number(badge?.void_count)||0,settled=Number(badge?.settled_submission_count)||0,decisive=w+l,rate=decisive?Math.round((w/decisive)*1000)/10:null;return{w,l,p,v,settled,decisive,rate};}
  function resultLabel(status){const s=String(status||'PENDING').toUpperCase();return s==='WON'?'WON':s==='LOST'?'LOST':s==='LIVE'?'LIVE':s==='PUSH'?'PUSH':s==='VOID'?'VOID':s==='UNRESOLVED'?'CHECKING':'VERIFIED PREGAME';}
  function decorateCommunity(){
    document.querySelectorAll('#profileCommunityGrid .community-card').forEach(card=>{
      const link=card.querySelector('a[href]');if(!link)return;const result=resultsByBuilder.get(normUrl(link.getAttribute('href')));if(!result)return;
      let node=card.querySelector('[data-pp-community-result]');if(!node){node=document.createElement('div');node.dataset.ppCommunityResult='1';card.insertBefore(node,link);}
      const status=String(result.result_status||'PENDING').toUpperCase();node.className=`pp-community-result pp-result-${status.toLowerCase()}`;node.innerHTML=`<strong>${esc(resultLabel(status))}</strong>${result.result_summary?`<span>${esc(result.result_summary)}</span>`:''}`;
    });
  }
  function render(badge,results){
    if(!badge)return;resultsByBuilder=new Map((results||[]).map(row=>[normUrl(row.builder_url),row]));
    const stats=recordStats(badge),handle=document.getElementById('profileHandle');
    if(handle&&!document.querySelector('[data-pp-growth-badges]')){const row=document.createElement('div');row.className='pp-growth-badges';row.dataset.ppGrowthBadges='1';const founder=badge.founding_number?`<span class="pp-founder-badge">FOUNDING MEMBER #${String(badge.founding_number).padStart(3,'0')}</span>`:'';const record=stats.settled?`<span class="pp-record-badge">VERIFIED RECORD ${stats.w}-${stats.l}${stats.p?` · ${stats.p}P`:''}</span>`:'<span class="pp-record-badge">VERIFIED RECORD · AWAITING RESULTS</span>';row.innerHTML=`${founder}${record}<span>${Number(badge.verified_submission_count)||0} verified submission${Number(badge.verified_submission_count)===1?'':'s'}</span><span>${Number(badge.invite_count)||0} invite${Number(badge.invite_count)===1?'':'s'}</span>`;handle.insertAdjacentElement('afterend',row);}
    const section=document.getElementById('communitySection');if(section&&!document.getElementById('ppReferralCard')){const link=referralUrl(badge.referral_code);const card=document.createElement('article');card.id='ppReferralCard';card.className='pp-referral-card';const recordCopy=stats.settled?`${stats.w}-${stats.l}${stats.p?` · ${stats.p} push`:''}${stats.v?` · ${stats.v} void`:''}${stats.rate!=null?` · ${stats.rate}% W-L win rate`:''}`:'Your public record begins when your first verified submission settles.';card.innerHTML=`<div><span class="eyebrow">YOUR VERIFIED COMMUNITY RECORD</span><h3>${esc(recordCopy)}</h3><p>Results are graded from the original pregame submission. Settled losses remain part of the record.</p></div><div class="pp-referral-stats"><span><strong>${Number(badge.verified_submission_count)||0}</strong> verified submissions</span><span><strong>${stats.settled}</strong> settled</span><span><strong>${Number(badge.invite_count)||0}</strong> members invited</span>${badge.founding_number?`<span><strong>#${String(badge.founding_number).padStart(3,'0')}</strong> founding member</span>`:''}</div><div><span class="eyebrow">YOUR REFERRAL LINK</span></div><div class="pp-referral-link"><code>${esc(link)}</code><button type="button" id="ppCopyReferral">Copy</button></div><p>Anyone who joins through this link is credited to your profile. Founding numbers are earned on a member's first verified submission.</p><a class="pp-submit-link" href="/submit">Submit another betslip →</a>`;const toolbar=section.querySelector('.tracking-toolbar');if(toolbar)toolbar.insertAdjacentElement('afterend',card);else section.prepend(card);card.querySelector('#ppCopyReferral')?.addEventListener('click',async event=>{try{await navigator.clipboard.writeText(link);event.currentTarget.textContent='Copied ✓';setTimeout(()=>event.currentTarget.textContent='Copy',1600);}catch{event.currentTarget.textContent='Copy failed';}});}
    decorateCommunity();const grid=document.getElementById('profileCommunityGrid');if(grid&&typeof MutationObserver==='function'&&!grid.dataset.ppResultObserver){grid.dataset.ppResultObserver='1';new MutationObserver(decorateCommunity).observe(grid,{childList:true,subtree:true});}
  }
  async function load(){const s=session();if(!s?.access_token)return false;try{const user=await getUser(s.access_token);if(!user?.id)return false;const [badge,results]=await Promise.all([getBadge(user.id,s.access_token),getResults(user.id,s.access_token)]);render(badge,results);return Boolean(badge);}catch{return false;}}
  async function init(){if(await load())return;setTimeout(load,1400);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();