const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
const SESSION_KEY='parlayping_supabase_session_v1';
const BOOK_DOMAINS={draftkings:'draftkings.com',fanduel:'fanduel.com',bet365:'bet365.com',caesars:'caesars.com',caesarssportsbook:'caesars.com',thescorebet:'thescore.bet',thescore:'thescore.bet',betmgm:'betmgm.com',fanatics:'betfanatics.com',fanaticssportsbook:'betfanatics.com',espnbet:'espnbet.com'};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const norm=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
let session=null,user=null,profile=null,tracks=[],community=[],activeFilter='all',pollTimer=null,refreshing=false;

function toast(message){const node=$('profileToast');if(!node)return;node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2500);}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
function setSession(value){try{if(value)localStorage.setItem(SESSION_KEY,JSON.stringify(value));else localStorage.removeItem(SESSION_KEY);}catch{}}
async function supabase(path,{method='GET',body,token,prefer}={}){const headers={apikey:SUPABASE_KEY,'content-type':'application/json'};if(token)headers.authorization=`Bearer ${token}`;if(prefer)headers.Prefer=prefer;const response=await fetch(`${SUPABASE_URL}${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let payload=null;try{payload=text?JSON.parse(text):null;}catch{payload={message:text};}if(!response.ok)throw new Error(payload?.message||payload?.error_description||payload?.error||`Request failed (${response.status})`);return payload;}
async function validSession(){let value=getSession();if(!value)return null;const exp=Number(value.expires_at||0)*1000;if(exp&&exp-Date.now()>=60000)return value;if(!value.refresh_token)return value;try{value=await supabase('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:value.refresh_token}});setSession(value);return value;}catch{setSession(null);return null;}}
function initials(value){return String(value||'PP').split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')||'PP';}
function safeAvatarUrl(value){try{const url=new URL(String(value||''),location.origin);return ['http:','https:'].includes(url.protocol)?url.href:null;}catch{return null;}}
function paintAvatar(node,name,url){if(!node)return;node.textContent='';const src=safeAvatarUrl(url);if(!src){node.textContent=initials(name);return;}const image=document.createElement('img');image.alt=`${name} profile picture`;image.decoding='async';image.src=src;image.addEventListener('error',()=>{node.textContent=initials(name);},{once:true});node.appendChild(image);}
function formatOdds(value){const n=Number(value);return Number.isFinite(n)?`${n>0?'+':''}${Math.round(n)}`:'—';}
function money(value){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(n):'—';}
function timeAgo(value){const time=new Date(value).getTime();if(!Number.isFinite(time))return '';const mins=Math.max(0,Math.floor((Date.now()-time)/60000));if(mins<1)return 'just now';if(mins<60)return `${mins}m ago`;const hours=Math.floor(mins/60);if(hours<24)return `${hours}h ago`;return `${Math.floor(hours/24)}d ago`;}
function trackingStatus(track){const status=String(track?.status||'UPCOMING').toUpperCase();return ['UPCOMING','LIVE','WON','LOST'].includes(status)?status:'UPCOMING';}
function statusLabel(status){return status==='WON'?'WINNER':status==='LOST'?'FINAL · LOSS':status;}
function marketText(leg){if(leg?.displayMarket)return String(leg.displayMarket);const market=String(leg?.market||'Prop');if(leg?.line!=null&&leg?.side)return `${String(leg.side).toUpperCase()} ${leg.line} · ${market}`;return market;}
function legStatus(leg){const value=String(leg?.status||'PENDING').toUpperCase();return ['PENDING','LIVE','HIT','MISS','PUSH','VOID','UNRESOLVED'].includes(value)?value:'PENDING';}
function bookLogo(book){const domain=BOOK_DOMAINS[norm(book)];if(!domain)return `<span>${esc(String(book||'PP').slice(0,2).toUpperCase())}</span>`;return `<img src="https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128" alt="${esc(book)} logo" loading="lazy" referrerpolicy="no-referrer">`;}
function progress(track){const total=Number(track?.leg_count)||track?.slip?.legs?.length||0,hit=Number(track?.hit_count)||0,miss=Number(track?.miss_count)||0,live=Number(track?.live_count)||0,pending=Number(track?.pending_count)||0;if(trackingStatus(track)==='WON')return `${total}/${total} legs hit`;if(trackingStatus(track)==='LOST')return `${hit}/${total} hit · ${miss} missed`;if(live)return `${hit}/${total} hit · ${live} live`;return `${pending} remaining`}
function cardStats(track){const type=track.tracking_type==='placed'?'PLACED':'WATCHING',odds=formatOdds(track.combined_odds_american);if(track.tracking_type==='placed'){const stake=track.stake_amount!=null?money(track.stake_amount):'Not entered';const payout=track.potential_payout!=null?money(track.potential_payout):'Not entered';return `<div class="card-stat"><small>Type</small><strong>${type}</strong></div><div class="card-stat"><small>Odds</small><strong>${odds}</strong></div><div class="card-stat"><small>Stake / payout</small><strong>${esc(stake)} · ${esc(payout)}</strong></div>`;}return `<div class="card-stat"><small>Type</small><strong>${type}</strong></div><div class="card-stat"><small>Odds</small><strong>${odds}</strong></div><div class="card-stat"><small>Progress</small><strong>${esc(progress(track))}</strong></div>`;}
function renderLeg(leg){const status=legStatus(leg),progressText=String(leg?.progressText||'').trim();return `<div class="leg leg-${status}"><div class="leg-copy"><strong>${esc(leg?.player||'Selection')}</strong><span>${esc(marketText(leg))}${leg?.matchup?` · ${esc(leg.matchup)}`:''}</span></div><div class="leg-progress"><strong>${esc(status==='PENDING'?'UPCOMING':status)}</strong>${progressText?`<span>${esc(progressText)}</span>`:''}</div></div>`;}
function renderTrack(track){const status=trackingStatus(track),legs=Array.isArray(track?.slip?.legs)?track.slip.legs:[],book=track.sportsbook||track.slip?.sportsbook||'',type=track.tracking_type==='placed'?'Placed':'Watching';return `<article class="tracking-card status-${status}" data-track-id="${esc(track.id)}"><div class="winner-ribbon">WINNER</div><div class="card-head"><div class="book-mark">${bookLogo(book||'ParlayPing')}</div><div class="card-title"><strong>${esc(track.title||`${legs.length}-Leg Parlay`)}</strong><span>${esc(type)}${book?` · ${esc(book)}`:''} · ${esc(timeAgo(track.created_at))}</span></div><span class="status-badge">${esc(statusLabel(status))}</span></div><div class="card-stats">${cardStats(track)}</div><div class="legs">${legs.map(renderLeg).join('')}</div><div class="card-footer"><a href="${esc(track.builder_url)}">Open Build</a><button type="button" class="share-progress" data-share-track="${esc(track.id)}">Share Progress</button></div></article>`;}
function matchesFilter(track){if(activeFilter==='all')return true;if(activeFilter==='watching')return track.tracking_type==='watching';return trackingStatus(track)===activeFilter;}
function renderTracks(){const grid=$('trackingGrid'),status=$('trackingStatus');if(!grid||!status)return;const rows=tracks.filter(matchesFilter);status.textContent=tracks.length?`${tracks.length} tracked parlay${tracks.length===1?'':'s'} · ${tracks.filter(row=>['LIVE','UPCOMING'].includes(trackingStatus(row))).length} active`:'No tracked parlays yet.';grid.innerHTML=rows.length?rows.map(renderTrack).join(''):'<div class="empty-card"><strong>Nothing in this view yet.</strong><span>Build a parlay and tap Track to add it here.</span></div>';grid.querySelectorAll('[data-share-track]').forEach(button=>button.addEventListener('click',()=>shareTrack(button.dataset.shareTrack)));updateMeta();}
function updateMeta(){const active=tracks.filter(row=>['LIVE','UPCOMING'].includes(trackingStatus(row))).length,placed=tracks.filter(row=>row.tracking_type==='placed').length,watching=tracks.filter(row=>row.tracking_type==='watching').length;if($('activeCount'))$('activeCount').textContent=`${active} active`;if($('placedCount'))$('placedCount').textContent=`${placed} placed`;if($('watchingCount'))$('watchingCount').textContent=`${watching} watching`;}
function renderProfile(){const name=profile?.display_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'ParlayPing User';$('profileName').textContent=name;paintAvatar($('profileAvatar'),name,profile?.avatar_url);const handle=String(profile?.x_username||'').replace(/^@/,'');$('profileHandle').textContent=handle?`@${handle}`:user?.email||'';}
function renderCommunity(){const grid=$('profileCommunityGrid'),status=$('profileCommunityStatus');if(!grid||!status)return;status.textContent=community.length?`${community.length} public build${community.length===1?'':'s'}`:'You have not posted a public build yet.';grid.innerHTML=community.length?community.map(post=>`<article class="community-card"><h3>${esc(post.title||'Community Parlay')}</h3><p>${esc([post.sport,`${post.leg_count||0} legs`,post.sportsbook,timeAgo(post.created_at)].filter(Boolean).join(' · '))}</p><a href="${esc(post.builder_url)}">Open build →</a></article>`).join(''):'<div class="empty-card"><strong>No public builds yet.</strong><span>Post one from the Community section on a build page.</span></div>';}
async function shareTrack(id){const track=tracks.find(row=>String(row.id)===String(id));if(!track)return;const status=trackingStatus(track),total=Number(track.leg_count)||track.slip?.legs?.length||0,hit=Number(track.hit_count)||0,live=Number(track.live_count)||0;let headline=status==='WON'?`WINNER — ${total}/${total} legs hit`:status==='LOST'?`FINAL — ${hit}/${total} legs hit`:status==='LIVE'?`${hit}/${total} legs hit · ${live} live`:`Tracking a ${total}-leg parlay`;const book=track.tracking_type==='placed'&&track.sportsbook?` on ${track.sportsbook}`:'';const text=`${headline}${book} with ParlayPing.`;try{if(navigator.share){await navigator.share({title:'ParlayPing Tracking',text,url:track.builder_url});return;}await navigator.clipboard.writeText(`${text} ${track.builder_url}`);toast('Tracking progress copied to clipboard.');}catch(error){if(error?.name!=='AbortError')toast('Could not share this tracking card.');}}
async function loadData(){
  const [trackRows,profileRows,communityRows]=await Promise.all([
    supabase(`/rest/v1/tracked_parlays?user_id=eq.${encodeURIComponent(user.id)}&select=id,user_id,source_token,builder_url,title,tracking_type,sportsbook,stake_amount,potential_payout,combined_odds_american,leg_count,slip,status,hit_count,miss_count,live_count,pending_count,is_public,last_refreshed_at,created_at,updated_at&order=created_at.desc`,{token:session.access_token}),
    supabase(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=display_name,x_username,avatar_url&limit=1`,{token:session.access_token}),
    supabase(`/rest/v1/community_parlays?user_id=eq.${encodeURIComponent(user.id)}&is_active=eq.true&select=id,builder_url,title,sport,leg_count,sportsbook,created_at&order=created_at.desc&limit=30`,{token:session.access_token}).catch(()=>[])
  ]);
  tracks=Array.isArray(trackRows)?trackRows:[];profile=Array.isArray(profileRows)?profileRows[0]||{}:{};community=Array.isArray(communityRows)?communityRows:[];renderProfile();renderTracks();renderCommunity();
}
function batches(rows,size=8){const out=[];for(let i=0;i<rows.length;i+=size)out.push(rows.slice(i,i+size));return out;}
function soonOrLive(track){if(trackingStatus(track)==='LIVE')return true;const starts=(track?.slip?.legs||[]).map(leg=>Date.parse(leg?.startTimeUTC||'')).filter(Number.isFinite);if(!starts.length)return false;const nearest=Math.min(...starts),delta=nearest-Date.now();return delta<=20*60*1000&&delta>-8*60*60*1000;}
async function persistRefresh(result){const body={slip:result.slip,status:result.status,hit_count:result.hitCount,miss_count:result.missCount,live_count:result.liveCount,pending_count:result.pendingCount,last_refreshed_at:result.refreshedAt,updated_at:new Date().toISOString()};await supabase(`/rest/v1/tracked_parlays?id=eq.${encodeURIComponent(result.id)}&user_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',token:session.access_token,prefer:'return=minimal',body});}
async function refreshRows(rows,{quiet=false}={}){
  if(refreshing||!rows.length)return;refreshing=true;const button=$('refreshTracking');if(button){button.disabled=true;button.textContent='↻ Updating…';}
  try{
    for(const batch of batches(rows,8)){
      const response=await fetch('/api/tracking-refresh',{method:'POST',headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:JSON.stringify({tracks:batch.map(row=>({id:row.id,slip:row.slip}))})});
      const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||`Refresh failed (${response.status})`);
      for(const result of payload.results||[]){if(!result?.id||result.error)continue;const index=tracks.findIndex(row=>String(row.id)===String(result.id));if(index>=0)tracks[index]={...tracks[index],slip:result.slip,status:result.status,hit_count:result.hitCount,miss_count:result.missCount,live_count:result.liveCount,pending_count:result.pendingCount,last_refreshed_at:result.refreshedAt};await persistRefresh(result);}
    }
    renderTracks();if(!quiet)toast('Tracking cards updated.');
  }catch(error){if(!quiet)toast(error.message);}
  finally{refreshing=false;if(button){button.disabled=false;button.textContent='↻ Refresh';}schedulePolling();}
}
async function refreshActive(manual=false){const active=tracks.filter(row=>['LIVE','UPCOMING'].includes(trackingStatus(row)));const rows=manual?active:active.filter(soonOrLive);return refreshRows(rows,{quiet:!manual});}
function schedulePolling(){clearTimeout(pollTimer);if(!tracks.some(row=>['LIVE','UPCOMING'].includes(trackingStatus(row))))return;const hasLive=tracks.some(row=>trackingStatus(row)==='LIVE');pollTimer=setTimeout(()=>refreshActive(false),hasLive?45000:120000);}
function wireFilters(){$('trackingFilters')?.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$('trackingFilters').querySelectorAll('[data-filter]').forEach(node=>node.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;renderTracks();}));}
function wireTabs(){document.querySelectorAll('[data-profile-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-profile-tab]').forEach(node=>node.classList.toggle('active',node===button));const tracking=button.dataset.profileTab==='tracking';$('trackingSection').hidden=!tracking;$('communitySection').hidden=tracking;}));}
async function init(){wireFilters();wireTabs();$('refreshTracking')?.addEventListener('click',()=>refreshActive(true));session=await validSession();if(!session?.access_token){$('signedOut').hidden=false;$('profileApp').hidden=true;return;}try{user=await supabase('/auth/v1/user',{token:session.access_token});if(!user?.id)throw new Error('Sign in required.');$('signedOut').hidden=true;$('profileApp').hidden=false;await loadData();await refreshActive(true);schedulePolling();}catch(error){setSession(null);$('profileApp').hidden=true;$('signedOut').hidden=false;toast(error.message);}}
init();
