(()=>{
  const $=id=>document.getElementById(id);
  function toast(message){const node=$('profileToast');if(!node)return;node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2600);}
  function ensureButton(){let button=$('movementAlerts');if(button)return button;const refresh=$('refreshTracking');if(!refresh)return null;const wrap=document.createElement('div');wrap.className='tracking-toolbar-actions';button=document.createElement('button');button.id='movementAlerts';button.type='button';button.className='refresh-button alert-button';button.textContent='🔔 Enable Alerts';wrap.append(button);refresh.parentNode.insertBefore(wrap,refresh);wrap.append(refresh);button.addEventListener('click',enable);return button;}
  async function sync(){const button=ensureButton();if(!button||!window.ParlayPingPush)return;try{const status=await window.ParlayPingPush.current();button.dataset.state=status.subscribed&&status.permission==='granted'?'on':status.permission;button.textContent=status.subscribed&&status.permission==='granted'?'🔔 Alerts On':'🔔 Enable Alerts';button.title=status.subscribed?'Movement alerts are enabled on this device.':'Notify me when tracked legs move or settle.';}catch{button.textContent='🔔 Enable Alerts';}}
  async function enable(){const button=ensureButton();if(!button||!window.ParlayPingPush)return;const old=button.textContent;button.disabled=true;button.textContent='Enabling…';try{await window.ParlayPingPush.enable();toast('Movement alerts enabled on this device.');}catch(error){toast(error?.message||'Could not enable movement alerts.');}finally{button.disabled=false;button.textContent=old;await sync();}}
  function focusTrack(){const id=new URLSearchParams(location.search).get('track');if(!id)return;let tries=0;const timer=setInterval(()=>{const card=document.querySelector(`.tracking-card[data-track-id="${CSS.escape(id)}"]`);if(card){clearInterval(timer);card.classList.add('notification-focus');card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>card.classList.remove('notification-focus'),3500);}else if(++tries>20)clearInterval(timer);},250);}
  window.addEventListener('DOMContentLoaded',()=>{ensureButton();sync();focusTrack();});
})();
