(()=>{
  const SESSION_KEY='parlayping_supabase_session_v1';
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const $=id=>document.getElementById(id);
  let accountData=null;

  function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
  function setSession(value){try{if(value)localStorage.setItem(SESSION_KEY,JSON.stringify(value));else localStorage.removeItem(SESSION_KEY);}catch{}}
  async function supabase(path,{method='GET',body}={}){const response=await fetch(`${SUPABASE_URL}${path}`,{method,headers:{apikey:SUPABASE_KEY,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||payload?.error_description||payload?.error||`Request failed (${response.status})`);return payload;}
  async function validSession(){let session=getSession();if(!session)return null;const exp=Number(session.expires_at||0)*1000;if(exp&&exp-Date.now()>=60000)return session;if(!session.refresh_token)return session;try{const fresh=await supabase('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}});setSession(fresh);return fresh;}catch{return session;}}
  async function api(path,{method='GET',body}={}){const session=await validSession();if(!session?.access_token)throw new Error('Sign in required.');const response=await fetch(path,{method,headers:{authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||`Request failed (${response.status})`);return payload;}
  function showStatus(message,error=false){const node=$('devStatus');if(!node)return;node.textContent=message;node.hidden=false;node.classList.toggle('error',error);}
  function clearStatus(){const node=$('devStatus');if(node){node.hidden=true;node.classList.remove('error');}}
  function moneyPlan(data){const sub=data?.subscription,usage=data?.usage||{};if(sub?.provider==='stripe'&&sub?.provider_subscription_id&&['active','trialing','past_due','unpaid'].includes(String(sub.status||'')))return String(sub.plan_id||usage.plan||'free').toLowerCase();return String(usage.plan||'free').toLowerCase();}
  function renderKeys(keys){const list=$('devKeysList');if(!list)return;list.innerHTML='';if(!keys?.length){list.innerHTML='<div class="dev-key-row"><div><strong>No API keys yet</strong><span>Create one when you need external API access.</span></div></div>';return;}for(const key of keys){const row=document.createElement('div');row.className='dev-key-row';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=key.name||'API key';const meta=document.createElement('span');meta.textContent=`${key.key_prefix||'pp_live_'}… · ${key.revoked_at?'revoked':key.last_used_at?'last used '+new Date(key.last_used_at).toLocaleString():'never used'}`;info.append(title,meta);const button=document.createElement('button');button.type='button';button.textContent=key.revoked_at?'Revoked':'Revoke';button.disabled=Boolean(key.revoked_at);button.addEventListener('click',()=>revokeKey(key.id));row.append(info,button);list.append(row);}}
  function renderDev(data){accountData=data;const usage=data.usage||{};$('devPlanName').textContent=String(usage.plan||'free').toUpperCase();$('devUsageUsed').textContent=usage.monthlyUsed??0;$('devUsageLimit').textContent=usage.monthlyLimit??0;$('devMinuteLimit').textContent=usage.rateLimitPerMinute??0;$('devKeyLimit').textContent=usage.maxApiKeys??0;renderKeys(data.apiKeys||[]);const sub=data.subscription||null,paid=sub?.provider==='stripe'&&Boolean(sub?.provider_subscription_id)&&['active','trialing','past_due','unpaid'].includes(String(sub?.status||''));const plan=moneyPlan(data);if(paid){$('devBillingSummary').textContent=`${plan==='business'?'Business':'Pro'} · ${String(sub.status||'active').replaceAll('_',' ')}`;$('devBillingFreeActions').hidden=true;$('devBillingPaidActions').hidden=false;}else{$('devBillingSummary').textContent='Free developer plan';$('devBillingFreeActions').hidden=false;$('devBillingPaidActions').hidden=true;}const billing=new URLSearchParams(location.search).get('billing');if(billing==='success')showStatus('Checkout completed. Stripe is syncing the developer plan.');if(billing==='cancelled')showStatus('Checkout cancelled. No billing change was made.');}

  function setTabUrl(tab){const url=new URL(location.href);if(tab==='tracking')url.searchParams.delete('tab');else url.searchParams.set('tab',tab);url.searchParams.delete('billing');history.replaceState({},'',url.pathname+(url.searchParams.toString()?`?${url.searchParams}`:''));}
  function activateDev(){if($('devTab')?.hidden)return;$('trackingSection').hidden=true;$('communitySection').hidden=true;$('devSection').hidden=false;document.querySelectorAll('[data-profile-tab]').forEach(node=>node.classList.toggle('active',node.id==='devTab'));setTabUrl('dev');if(!accountData)loadDeveloper().catch(error=>showStatus(error.message,true));}
  function wireTabs(){document.querySelectorAll('[data-profile-tab]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.profileTab==='dev'){activateDev();return;}$('devSection').hidden=true;setTabUrl(button.dataset.profileTab==='community'?'community':'tracking');}));}
  function applyRequestedTab(){const requested=new URLSearchParams(location.search).get('tab');if(requested==='dev'&&!$('devTab')?.hidden){activateDev();return;}if(requested==='community')document.querySelector('[data-profile-tab="community"]')?.click();}

  async function loadDeveloper(){const data=await api('/api/account');const devTab=$('devTab');if(!data.isDeveloper){if(devTab)devTab.hidden=true;if(new URLSearchParams(location.search).get('tab')==='dev'){document.querySelector('[data-profile-tab="tracking"]')?.click();}return false;}if(devTab)devTab.hidden=false;renderDev(data);return true;}
  async function refreshDeveloper(){const allowed=await loadDeveloper();if(!allowed)throw new Error('Developer access is restricted.');}
  async function revokeKey(id){if(!id||!confirm('Revoke this API key? This cannot be undone.'))return;clearStatus();try{await api('/api/api-keys',{method:'DELETE',body:{id}});showStatus('API key revoked.');await refreshDeveloper();}catch(error){showStatus(error.message,true);}}
  async function createKey(event){event.preventDefault();clearStatus();const name=String($('devKeyName')?.value||'').trim();if(!name)return;const button=event.submitter,old=button?.textContent;if(button){button.disabled=true;button.textContent='Creating…';}try{const result=await api('/api/api-keys',{method:'POST',body:{name}});$('devNewKey').textContent=result.key?.key||'';$('devNewKeyBox').hidden=false;$('devKeyName').value='';showStatus('API key created. Copy it now; it will not be shown again.');await refreshDeveloper();}catch(error){showStatus(error.message,true);}finally{if(button){button.disabled=false;button.textContent=old;}}}
  async function checkout(plan){clearStatus();try{const result=await api('/api/billing-checkout',{method:'POST',body:{plan}});if(!result?.url)throw new Error('Checkout URL was not returned.');location.assign(result.url);}catch(error){showStatus(error.message,true);}}
  async function portal(){clearStatus();try{const result=await api('/api/billing-portal',{method:'POST'});if(!result?.url)throw new Error('Billing portal URL was not returned.');location.assign(result.url);}catch(error){showStatus(error.message,true);}}

  function init(){wireTabs();$('devKeyForm')?.addEventListener('submit',createKey);$('devUpgradePro')?.addEventListener('click',()=>checkout('pro'));$('devUpgradeBusiness')?.addEventListener('click',()=>checkout('business'));$('devManageBilling')?.addEventListener('click',portal);loadDeveloper().then(()=>applyRequestedTab()).catch(()=>{const tab=$('devTab');if(tab)tab.hidden=true;applyRequestedTab();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
