(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SESSION_KEY='parlayping_supabase_session_v1';
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
  async function getUser(token){const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return null;return r.json();}
  async function getBadge(userId,token){const r=await fetch(`${SUPABASE_URL}/rest/v1/member_badges?user_id=eq.${encodeURIComponent(userId)}&select=referral_code,founding_number,invite_count,verified_submission_count&limit=1`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}});if(!r.ok)return null;const rows=await r.json();return Array.isArray(rows)?rows[0]||null:null;}
  function referralUrl(code){return `${location.origin}/join/${encodeURIComponent(code)}`;}
  function render(badge){
    if(!badge)return;const handle=document.getElementById('profileHandle');if(handle&&!document.querySelector('[data-pp-growth-badges]')){const row=document.createElement('div');row.className='pp-growth-badges';row.dataset.ppGrowthBadges='1';const founder=badge.founding_number?`<span class="pp-founder-badge">FOUNDING MEMBER #${String(badge.founding_number).padStart(3,'0')}</span>`:'';row.innerHTML=`${founder}<span>${Number(badge.verified_submission_count)||0} verified submission${Number(badge.verified_submission_count)===1?'':'s'}</span><span>${Number(badge.invite_count)||0} invite${Number(badge.invite_count)===1?'':'s'}</span>`;handle.insertAdjacentElement('afterend',row);}
    const section=document.getElementById('communitySection');if(section&&!document.getElementById('ppReferralCard')){const link=referralUrl(badge.referral_code);const card=document.createElement('article');card.id='ppReferralCard';card.className='pp-referral-card';card.innerHTML=`<div><span class="eyebrow">GROW PARLAYPING</span><h3>Your referral link</h3><p>Anyone who joins through this link is credited to your profile. Founding numbers are earned on a member's first verified submission.</p></div><div class="pp-referral-link"><code>${esc(link)}</code><button type="button" id="ppCopyReferral">Copy</button></div><div class="pp-referral-stats"><span><strong>${Number(badge.invite_count)||0}</strong> members invited</span><span><strong>${Number(badge.verified_submission_count)||0}</strong> verified submissions</span>${badge.founding_number?`<span><strong>#${String(badge.founding_number).padStart(3,'0')}</strong> founding member</span>`:''}</div><a class="pp-submit-link" href="/submit">Submit another betslip →</a>`;const toolbar=section.querySelector('.tracking-toolbar');if(toolbar)toolbar.insertAdjacentElement('afterend',card);else section.prepend(card);card.querySelector('#ppCopyReferral')?.addEventListener('click',async event=>{try{await navigator.clipboard.writeText(link);event.currentTarget.textContent='Copied ✓';setTimeout(()=>event.currentTarget.textContent='Copy',1600);}catch{event.currentTarget.textContent='Copy failed';}});}
  }
  async function load(){const s=session();if(!s?.access_token)return false;try{const user=await getUser(s.access_token);if(!user?.id)return false;const badge=await getBadge(user.id,s.access_token);render(badge);return Boolean(badge);}catch{return false;}}
  async function init(){if(await load())return;setTimeout(load,1400);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();