(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SESSION_KEY='parlayping_supabase_session_v1';
  const CONFIG_URL=`${SUPABASE_URL}/functions/v1/parlayping-push-config`;

  function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
  function supported(){return Boolean(window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window);}
  function urlBase64ToUint8Array(value){const padding='='.repeat((4-value.length%4)%4);const base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));}
  async function register(){if(!supported())throw new Error('Push notifications are not available in this browser. On iPhone, add ParlayPing to your Home Screen and open it there.');const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready;return registration;}
  async function user(session){const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${session.access_token}`}});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.id)throw new Error(payload?.message||'Sign in again to enable notifications.');return payload;}
  async function publicKey(session){const response=await fetch(CONFIG_URL,{method:'POST',headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${session.access_token}`,'content-type':'application/json'},body:'{}'});const payload=await response.json().catch(()=>({}));if(!response.ok||!payload?.publicKey)throw new Error(payload?.error||'Push setup is temporarily unavailable.');return payload.publicKey;}
  async function saveSubscription(session,userId,subscription){const json=subscription.toJSON();const body={user_id:userId,endpoint:json.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth,user_agent:navigator.userAgent,enabled:true,updated_at:new Date().toISOString()};if(!body.endpoint||!body.p256dh||!body.auth)throw new Error('The browser did not return a complete push subscription.');const response=await fetch(`${SUPABASE_URL}/rest/v1/push_subscriptions?on_conflict=user_id%2Cendpoint`,{method:'POST',headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${session.access_token}`,'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload?.message||`Could not save notification subscription (${response.status}).`);}}
  async function enable(){const session=getSession();if(!session?.access_token)throw new Error('Sign in to enable ParlayPing movement alerts.');if(!supported())throw new Error('Push notifications are not available in this browser. On iPhone, add ParlayPing to your Home Screen and open it there.');let permission=Notification.permission;if(permission==='default')permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notifications are turned off for ParlayPing.');const registration=await register();const [key,account]=await Promise.all([publicKey(session),user(session)]);let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(key)});await saveSubscription(session,account.id,subscription);return{ok:true,permission,subscription};}
  async function current(){if(!supported())return{supported:false,permission:'unsupported',subscribed:false};const registration=await navigator.serviceWorker.getRegistration('/');const subscription=registration?await registration.pushManager.getSubscription():null;return{supported:true,permission:Notification.permission,subscribed:Boolean(subscription)};}
  async function showLocal({title='ParlayPing Tracking',body='',url='/profile?tab=tracking',tag='parlayping-tracking'}={}){if(!supported()||Notification.permission!=='granted')return false;const registration=await register();await registration.showNotification(title,{body,icon:'/parlayping-approved-logo.png',badge:'/parlayping-approved-logo.png',tag,data:{url}});return true;}
  window.ParlayPingPush={supported,current,enable,showLocal,register};
})();
