(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SESSION_KEY='parlayping_supabase_session_v1';
  let referralCode=null,foundingNumber=null;
  function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;}}
  async function badge(){const s=session();if(!s?.access_token)return null;const u=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${s.access_token}`}});if(!u.ok)return null;const user=await u.json();if(!user?.id)return null;const r=await fetch(`${SUPABASE_URL}/rest/v1/member_badges?user_id=eq.${encodeURIComponent(user.id)}&select=referral_code,founding_number&limit=1`,{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${s.access_token}`}});if(!r.ok)return null;const rows=await r.json();return Array.isArray(rows)?rows[0]||null:null;}
  function withReferral(raw){if(!raw||raw==='#'||!referralCode)return raw;try{const url=new URL(raw,location.origin);url.searchParams.set('ref',referralCode);return url.toString();}catch{return raw;}}
  function decorate(){const link=document.getElementById('openShare');if(link&&link.getAttribute('href')&&link.getAttribute('href')!=='#'){const next=withReferral(link.href);if(next&&link.href!==next)link.href=next;}const card=document.querySelector('.founding-card');if(card&&foundingNumber&&!card.querySelector('[data-pp-founder-self]')){const chip=document.createElement('div');chip.dataset.ppFounderSelf='1';chip.style.cssText='margin-top:12px;padding:9px 11px;border-radius:12px;background:rgba(72,220,205,.1);border:1px solid rgba(72,220,205,.28);color:#7be8dd;font-size:12px;font-weight:900;letter-spacing:.05em';chip.textContent=`YOU ARE FOUNDING MEMBER #${String(foundingNumber).padStart(3,'0')}`;card.appendChild(chip);}}
  function shareText(){const title=document.getElementById('successTitle')?.textContent?.trim()||'My betslip';const share=withReferral(document.getElementById('openShare')?.href||'');const join=referralCode?`${location.origin}/join?ref=${encodeURIComponent(referralCode)}&next=%2Fsubmit`:`${location.origin}/submit`;return `✓ ${title} verified pregame with ParlayPing. View it, tail it, or make your own changes: ${share}\n\nSubmit yours free: ${join}`;}
  async function intercept(event){const target=event.target.closest?.('#copyResult,#shareResult');if(!target||!referralCode||document.getElementById('submitSuccess')?.hidden)return;event.preventDefault();event.stopImmediatePropagation();const text=shareText(),status=document.getElementById('submitStatus');try{if(target.id==='shareResult'&&navigator.share){await navigator.share({title:document.getElementById('successTitle')?.textContent||'ParlayPing verified betslip',text,url:withReferral(document.getElementById('openShare')?.href||'')});return;}await navigator.clipboard.writeText(text);if(status){status.textContent='Referral share post copied.';status.className='submit-status success';}}catch(error){if(error?.name!=='AbortError'&&status){status.textContent='Could not share automatically.';status.className='submit-status error';}}}
  async function init(){try{const row=await badge();referralCode=row?.referral_code||null;foundingNumber=row?.founding_number||null;}catch{}decorate();const root=document.getElementById('submitSuccess');if(root&&typeof MutationObserver==='function')new MutationObserver(decorate).observe(root,{attributes:true,subtree:true,attributeFilter:['href','hidden']});document.addEventListener('click',intercept,true);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();