(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SPORTS=['ALL','NFL','NCAAF','NBA','WNBA','NCAAB','MLB','NHL'];
  const SORTS=[['attention','High attention'],['probability','Probability'],['social','Likes + reposts']];
  const PROP_FILTERS=[['ALL','All props'],['TD','Touchdowns'],['REC_YDS','Receiving yards'],['RECEPTIONS','Receptions'],['RUSH_YDS','Rushing yards'],['PASSING','Passing'],['OTHER','Other props']];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const q=s=>document.querySelector(s);
  const norm=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'').trim();
  let rows=[],players=[],selections=[],communityRows=[],sport='ALL',sort='attention',visible=24,pulseTab='players',propFilter='ALL',loading=false;

  function compact(v){const n=Number(v)||0;if(n>=1e6)return`${(n/1e6).toFixed(n>=1e7?0:1)}M`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e4?0:1)}K`;return String(Math.round(n));}
  function pctText(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n))return null;if(n>0&&n<.1)return'<0.1%';return`${n.toFixed(n%1?1:0)}%`;}
  function formatStart(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'upcoming';return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(t));}
  function age(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'recently';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`;}
  function upcoming(r){const t=Date.parse(r?.event_start_at||'');return Number.isFinite(t)&&t>Date.now();}
  function socialScore(r){return (Number(r.like_count)||0)+(Number(r.repost_count)||0);}
  function probability(r){const v=r?.bet_probability_pct;if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
  function probabilitySource(r){if(r?._source==='community')return'ParlayPing model';return String(r?.probability_kind||'').startsWith('market-implied')?'Market-implied':'ParlayPing model';}
  function barWidth(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return 0;return Math.max(.8,Math.min(100,n));}
  function legStart(leg){return Date.parse(leg?.startTimeUTC||leg?.start_time_utc||'');}
  function communityStart(post){const starts=(post?.legs||[]).map(legStart).filter(Number.isFinite);return starts.length?new Date(Math.min(...starts)).toISOString():null;}
  function legLabel(leg){const player=String(leg?.player||'Selection'),market=String(leg?.displayMarket||leg?.display_market||leg?.market||'Prop');return `${player} — ${market}`;}
  function normalizeCommunity(post){const legs=Array.isArray(post?.legs)?post.legs:[];return {_source:'community',id:post.id,builder_url:post.builder_url,title:post.title,author_name:post.author_name,x_username:post.x_username,sport:post.sport,event_start_at:communityStart(post),created_at:post.created_at,source_url:post.source_url,bet_probability_pct:post.bet_probability_pct,analysis_summary:post.analysis_summary,legs,original_text:legs.slice(0,4).map(legLabel).join(' · '),attention_score:0,like_count:0,repost_count:0,reply_count:0};}

  function sorted(){let out=rows.filter(upcoming).filter(r=>sport==='ALL'||String(r.sport||'').toUpperCase()===sport);out=[...out];if(sort==='probability')out.sort((a,b)=>(probability(b)??-1)-(probability(a)??-1)||Number(b.attention_score||0)-Number(a.attention_score||0));else if(sort==='social')out.sort((a,b)=>socialScore(b)-socialScore(a)||Number(b.attention_score||0)-Number(a.attention_score||0));else out.sort((a,b)=>Number(b.attention_score||0)-Number(a.attention_score||0)||Date.parse(b.created_at||b.last_verified_at||0)-Date.parse(a.created_at||a.last_verified_at||0));return out;}

  function propGroup(r){const m=String(r?.market||'').toLowerCase(),d=String(r?.display_market||r?.displayMarket||'').toLowerCase();if(/\batd\b|firsttd|firsthalftd|touchdown|td scorer|first td/.test(`${m} ${d}`))return'TD';if(/recyds|receiving/.test(`${m} ${d}`))return'REC_YDS';if(/receptions|\brec\b/.test(`${m} ${d}`))return'RECEPTIONS';if(/rushyds|rushing/.test(`${m} ${d}`))return'RUSH_YDS';if(/passyds|passing|passtd|completions|attempts|interceptions/.test(`${m} ${d}`))return'PASSING';return'OTHER';}
  function pulseKey(row){return [norm(row?.player),norm(row?.market),norm(row?.side),String(row?.line??'')].join('|');}
  function propRank(a,b){const score=r=>Number(r.community_count||0)*140+Number(r.observed_count||0)*100+Number(r.verified_count||0)*25+Number(r.attention_score||0);return score(b)-score(a)||socialScore(b)-socialScore(a);}
  function diversifiedProps(source,limit=12){const groups=['TD','REC_YDS','RECEPTIONS','RUSH_YDS','PASSING','OTHER'],buckets=new Map(groups.map(g=>[g,[]]));source.forEach(r=>buckets.get(propGroup(r))?.push(r));buckets.forEach(list=>list.sort(propRank));const out=[],seen=new Set();for(let round=0;round<3&&out.length<limit;round++)for(const g of groups){const item=buckets.get(g)?.[round];if(item&&!seen.has(item.selection_key)){seen.add(item.selection_key);out.push(item);if(out.length>=limit)break;}}if(out.length<limit){for(const item of [...source].sort(propRank)){if(seen.has(item.selection_key))continue;seen.add(item.selection_key);out.push(item);if(out.length>=limit)break;}}return out;}
  function mergeCommunityPulse(xPlayers,xSelections,community){
    const selectionMap=new Map(),playerMap=new Map();
    for(const row of xSelections||[]){const copy={...row,community_count:0};selectionMap.set(pulseKey(copy),copy);}
    for(const row of xPlayers||[]){playerMap.set(norm(row.player),{...row,community_count:0,__markets:new Set()});}
    for(const post of community||[]){if(String(post?.sport||'').toUpperCase()!=='NFL')continue;const legs=(post?.legs||[]).filter(leg=>String(leg?.sport||'').toUpperCase()==='NFL'&&Number.isFinite(legStart(leg))&&legStart(leg)>Date.now()),seenSelections=new Set(),seenPlayers=new Set();for(const leg of legs){if(!leg?.player||!leg?.market)continue;const key=pulseKey(leg);if(!seenSelections.has(key)){seenSelections.add(key);let row=selectionMap.get(key);if(!row){const pre=Number(leg.pregameProbability);row={selection_key:`community:${key}`,sport:'NFL',player:leg.player,market:leg.market,side:leg.side||null,line:leg.line??null,display_market:leg.displayMarket||leg.originalText||leg.market,observed_count:0,verified_count:0,community_count:0,like_count:0,repost_count:0,reply_count:0,attention_score:0,avg_leg_probability_pct:Number.isFinite(pre)?(pre<=1?pre*100:pre):null,earliest_start_at:leg.startTimeUTC||null};selectionMap.set(key,row);}row.community_count=Number(row.community_count||0)+1;if(!row.community_builder_url)row.community_builder_url=post.builder_url;}
        const pk=norm(leg.player);if(!seenPlayers.has(pk)){seenPlayers.add(pk);let p=playerMap.get(pk);if(!p){p={player:leg.player,observed_count:0,verified_count:0,community_count:0,attention_score:0,like_count:0,repost_count:0,prop_market_count:0,__markets:new Set()};playerMap.set(pk,p);}p.community_count=Number(p.community_count||0)+1;}const p=playerMap.get(pk);p.__markets.add(String(leg.market));}}
    for(const p of playerMap.values())p.prop_market_count=Math.max(Number(p.prop_market_count||0),p.__markets.size);
    return{players:[...playerMap.values()].map(({__markets,...row})=>row),selections:[...selectionMap.values()]};
  }

  function renderControls(){q('#trendSportFilters').innerHTML=SPORTS.map(s=>`<button class="trend-pill${sport===s?' active':''}" type="button" data-sport="${s}">${s==='ALL'?'All':s}</button>`).join('');q('#trendSortFilters').innerHTML=SORTS.map(([key,label])=>`<button class="trend-pill${sort===key?' active':''}" type="button" data-sort="${key}">${label}</button>`).join('');}
  function renderPropFilters(){const box=q('#pulseMarketFilters');if(!box)return;box.hidden=pulseTab!=='selections';box.innerHTML=PROP_FILTERS.map(([key,label])=>`<button class="pulse-market${propFilter===key?' active':''}" type="button" data-prop-filter="${key}">${label}</button>`).join('');}
  function pulseMetric(row){const community=Number(row.community_count||0),observed=Number(row.observed_count||0),verified=Number(row.verified_count||0);if(community)return`${community} community · ${observed} cached X`;return`${observed} cached X · ${verified} verified`;}
  function pulseCard(row,type){const prob=pctText(row.avg_leg_probability_pct),social=`♥ ${compact(row.like_count)} · ↻ ${compact(row.repost_count)}`,strength=Math.min(100,Math.max(5,(Number(row.observed_count||0)+Number(row.community_count||0)*2)*10));if(type==='players')return `<article class="pulse-card"><div class="pulse-card-top"><span>NFL</span><b>${esc(pulseMetric(row))}</b></div><strong>${esc(row.player||'Unknown')}</strong><p>${Number(row.prop_market_count||0)} prop market${Number(row.prop_market_count||0)===1?'':'s'}${Number(row.observed_count||0)?` · ${esc(social)}`:''}</p><div class="pulse-strength"><span style="width:${strength}%"></span></div></article>`;const link=row.community_builder_url?`<a href="${esc(row.community_builder_url)}">Community build →</a>`:row.sample_tweet_id&&Number(row.verified_count||0)>0?`<a href="/verified/${esc(row.sample_tweet_id)}">Verified X example →</a>`:'';return `<article class="pulse-card"><div class="pulse-card-top"><span>${esc(PROP_FILTERS.find(([k])=>k===propGroup(row))?.[1]||'NFL prop')}</span><b>${esc(pulseMetric(row))}</b></div><strong>${esc(row.player||'Unknown')}</strong><p>${esc(row.display_market||row.market||'Selection')}${prob?` · ${esc(prob)}`:''}</p><div class="pulse-card-foot"><span>${Number(row.observed_count||0)?esc(social):'Community verified'}</span>${link}</div></article>`;}
  function renderPulse(){document.querySelectorAll('[data-pulse-tab]').forEach(b=>b.classList.toggle('active',b.dataset.pulseTab===pulseTab));renderPropFilters();let source;if(pulseTab==='players'){source=[...players].sort((a,b)=>(Number(b.community_count||0)+Number(b.observed_count||0))-(Number(a.community_count||0)+Number(a.observed_count||0))||Number(b.attention_score||0)-Number(a.attention_score||0)).slice(0,12);}else{const all=[...selections].filter(r=>String(r.sport||'').toUpperCase()==='NFL');source=propFilter==='ALL'?diversifiedProps(all,12):all.filter(r=>propGroup(r)===propFilter).sort(propRank).slice(0,12);}const grid=q('#pulseGrid');grid.innerHTML=source.length?source.map(r=>pulseCard(r,pulseTab)).join(''):'<div class="pulse-loading">No upcoming NFL community or cached-X props match this view yet.</div>';}

  function communityCard(r){const p=probability(r),probText=p!=null?`ParlayPing model ${pctText(p)}`:'Pregame verified',bar=p!=null?`<div class="trend-probability"><div class="trend-probability-head"><span>ParlayPing model probability</span><b>${esc(pctText(p))}</b></div><div class="trend-probbar"><span style="width:${barWidth(p)}%"></span></div></div>`:'',author=r.x_username?`@${r.x_username}`:(r.author_name||'ParlayPing member'),source=r.source_url?`<a class="trend-x" href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">Original X ↗</a>`:'';return `<article class="trend-card"><div class="trend-verify-row"><a class="verified-badge" href="${esc(r.builder_url)}">✓ COMMUNITY VERIFIED</a><span>${esc(r.sport||'SPORTS')} · ${esc(formatStart(r.event_start_at))}</span></div><div class="trend-top"><strong class="trend-author">${esc(author)}</strong><span class="trend-prob">${esc(probText)}</span></div><p class="trend-text"><strong>${esc(r.title||'Community Parlay')}</strong><br>${esc(r.original_text||'Verified community betslip')}</p><p class="trend-analysis">${esc(r.analysis_summary||'Every leg was verified pregame by ParlayPing.')}</p>${bar}<div class="trend-meta"><b>Community submission</b><span>${esc(r.legs?.length||0)} legs</span></div><span class="trend-note">Submitted ${esc(age(r.created_at))} · screenshot not retained</span><div class="trend-actions"><a class="trend-add" href="${esc(r.builder_url)}">Open Builder</a>${source}<a class="trend-x" href="/submit">Submit yours</a></div></article>`;}
  function xCard(r){const p=probability(r),source=probabilitySource(r),probText=p!=null?`${source} ${pctText(p)}`:'Probability unavailable',bar=p!=null?`<div class="trend-probability"><div class="trend-probability-head"><span>${esc(source)} probability</span><b>${esc(pctText(p))}</b></div><div class="trend-probbar"><span style="width:${barWidth(p)}%"></span></div></div>`:'',author=r.author_username?`@${r.author_username}`:(r.author_name||'X user'),media=r.media_url?`<a class="trend-media" href="/verified/${esc(r.tweet_id)}"><img src="${esc(r.media_url)}" alt="Verified public betslip from ${esc(author)}" loading="lazy" decoding="async"></a>`:'';return `<article class="trend-card"><div class="trend-verify-row"><a class="verified-badge" href="/verified/${esc(r.tweet_id)}">✓ VERIFIED X BETSLIP</a><span>${esc(r.sport||'SPORTS')} · ${esc(formatStart(r.event_start_at))}</span></div>${media}<div class="trend-top"><strong class="trend-author">${esc(author)}</strong><span class="trend-prob">${esc(probText)}</span></div><p class="trend-text">${esc(r.original_text||'Public betslip on X')}</p><p class="trend-analysis">${esc(r.analysis_summary||'Verified pregame by ParlayPing.')}</p>${bar}<div class="trend-meta"><b>Attention ${esc(Number(r.attention_score||0).toFixed(1))}</b><span>♥ ${esc(compact(r.like_count))}</span><span>↻ ${esc(compact(r.repost_count))}</span><span>↩ ${esc(compact(r.reply_count))}</span></div><span class="trend-note">Verified ${esc(age(r.last_verified_at||r.first_verified_at))} · cached public X source</span><div class="trend-actions"><button class="trend-add" type="button" data-add="${esc(r.tweet_id)}">Add to Betslip</button><a class="trend-x" href="/verified/${esc(r.tweet_id)}">Verification</a><a class="trend-x" href="${esc(r.tweet_url)}" target="_blank" rel="noopener noreferrer">X ↗</a></div></article>`;}
  function card(r){return r?._source==='community'?communityCard(r):xCard(r);}
  function render(){renderControls();renderPulse();const all=rows.filter(upcoming),scope=sorted(),shown=scope.slice(0,visible);q('#trendCount').textContent=String(all.length);q('#trendStatus').textContent=all.length?`${scope.length} verified upcoming bet${scope.length===1?'':'s'} · ${communityRows.filter(p=>upcoming(normalizeCommunity(p))).length} community · live X crawling off`:'No verified upcoming bets yet — submit the first one.';q('#trendGrid').innerHTML=shown.length?shown.map(card).join(''):'<div class="trend-empty">No verified upcoming betslips match this filter. <a href="/submit">Submit one →</a></div>';const more=q('#trendLoadMore');more.hidden=shown.length>=scope.length;more.textContent=`Show more trending bets (${scope.length-shown.length} remaining)`;}

  async function get(path){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY}});if(!res.ok)throw new Error(`Feed unavailable (${res.status})`);return res.json();}
  async function load(){if(loading)return;loading=true;q('#trendRefresh').disabled=true;q('#trendStatus').textContent='Refreshing verified community + cached X trends…';const now=encodeURIComponent(new Date().toISOString());try{const [feed,xPlayers,xSelections,community]=await Promise.all([get(`x_verified_betslips?event_start_at=gt.${now}&select=tweet_id,tweet_url,author_username,author_name,sport,original_text,media_url,source_created_at,event_start_at,event_label,first_verified_at,last_verified_at,bet_probability_pct,probability_kind,analysis_summary,like_count,repost_count,reply_count,attention_score&order=attention_score.desc,last_verified_at.desc&limit=150`),get('x_nfl_player_pulse?select=*&order=observed_count.desc,attention_score.desc&limit=100'),get('x_nfl_prop_pulse?select=*&order=observed_count.desc,attention_score.desc&limit=250'),get('community_parlays?verified_pregame=eq.true&is_active=eq.true&select=id,builder_url,title,author_name,x_username,sport,leg_count,legs,source_url,bet_probability_pct,analysis_summary,created_at&order=created_at.desc&limit=150')]);communityRows=Array.isArray(community)?community:[];const pulse=mergeCommunityPulse(Array.isArray(xPlayers)?xPlayers:[],Array.isArray(xSelections)?xSelections:[],communityRows);players=pulse.players;selections=pulse.selections;rows=[...(Array.isArray(feed)?feed:[]),...communityRows.map(normalizeCommunity)];visible=24;render();}catch(e){rows=[];players=[];selections=[];communityRows=[];q('#trendGrid').innerHTML=`<div class="trend-empty trend-danger">${esc(e.message||'Could not load trending bets.')}</div>`;q('#trendStatus').textContent='Trending feed unavailable.';renderPulse();}finally{loading=false;q('#trendRefresh').disabled=false;}}
  async function add(id,button){button.disabled=true;button.textContent='Opening Builder…';try{const res=await fetch('/api/trending-build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tweet_id:id})}),p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||`Could not add bet (${res.status})`);location.assign(p.builderUrl);}catch(e){button.disabled=false;button.textContent='Add to Betslip';alert(e.message||'Could not add this bet to Builder.');}}
  function wire(){document.addEventListener('click',e=>{const pt=e.target.closest('[data-pulse-tab]');if(pt){pulseTab=pt.dataset.pulseTab||'players';propFilter='ALL';renderPulse();return;}const pf=e.target.closest('[data-prop-filter]');if(pf){propFilter=pf.dataset.propFilter||'ALL';renderPulse();return;}const s=e.target.closest('[data-sport]');if(s){sport=s.dataset.sport||'ALL';visible=24;render();return;}const so=e.target.closest('[data-sort]');if(so){sort=so.dataset.sort||'attention';visible=24;render();return;}const addBtn=e.target.closest('[data-add]');if(addBtn){add(addBtn.dataset.add,addBtn);}});q('#trendLoadMore').addEventListener('click',()=>{visible+=24;render();});q('#trendRefresh').addEventListener('click',load);}
  function init(){wire();renderControls();load();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
