(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SPORTS=['ALL','NFL','NCAAF','NBA','WNBA','NCAAB','MLB','NHL'];
  const SORTS=[['attention','High attention'],['probability','Probability'],['social','Likes + reposts']];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let rows=[],sport='ALL',sort='attention',visible=18,loading=false;
  const q=s=>document.querySelector(s);
  function compact(v){const n=Number(v)||0;if(n>=1e6)return`${(n/1e6).toFixed(n>=1e7?0:1)}M`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e4?0:1)}K`;return String(Math.round(n));}
  function formatStart(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'upcoming';return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(t));}
  function age(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'recently';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`;}
  function upcoming(r){const t=Date.parse(r?.event_start_at||'');return r?.is_pregame_confirmed===true&&r?.builder_ready===true&&Number.isFinite(t)&&t>Date.now();}
  function socialScore(r){return (Number(r.like_count)||0)+(Number(r.repost_count)||0);}
  function probability(r){const n=Number(r.bet_probability_pct);return Number.isFinite(n)?n:null;}
  function sorted(){let out=rows.filter(upcoming).filter(r=>sport==='ALL'||String(r.sport||'').toUpperCase()===sport);out=[...out];if(sort==='probability')out.sort((a,b)=>(probability(b)??-1)-(probability(a)??-1)||Number(b.attention_score||0)-Number(a.attention_score||0));else if(sort==='social')out.sort((a,b)=>socialScore(b)-socialScore(a)||Number(b.attention_score||0)-Number(a.attention_score||0));else out.sort((a,b)=>Number(b.attention_score||0)-Number(a.attention_score||0)||socialScore(b)-socialScore(a));return out;}
  function renderControls(){q('#trendSportFilters').innerHTML=SPORTS.map(s=>`<button class="trend-pill${sport===s?' active':''}" type="button" data-sport="${s}">${s==='ALL'?'All':s}</button>`).join('');q('#trendSortFilters').innerHTML=SORTS.map(([key,label])=>`<button class="trend-pill${sort===key?' active':''}" type="button" data-sort="${key}">${label}</button>`).join('');}
  function card(r){const p=probability(r),probText=p!=null?`${p.toFixed(p%1?1:0)}% model`:String(r.probability_kind||'').includes('correlated')?'Model withheld':'Model unavailable';const author=r.author_username?`@${r.author_username}`:(r.author_name||'X user'),media=r.media_url?`<a class="trend-media" href="${esc(r.tweet_url)}" target="_blank" rel="noopener noreferrer"><img src="${esc(r.media_url)}" alt="Public betslip from ${esc(author)}" loading="lazy"></a>`:'';return `<article class="trend-card"><div class="trend-top"><span>${esc(r.sport||'SPORTS')} · ${esc(formatStart(r.event_start_at))}</span><span class="trend-prob">${esc(probText)}</span></div>${media}<strong class="trend-author">${esc(author)}</strong><p class="trend-text">${esc(r.text||'Public betslip on X')}</p><p class="trend-analysis">${esc(r.analysis_summary||'Pregame verified by ParlayPing.')}</p><div class="trend-meta"><b>Attention ${esc(Number(r.attention_score||0).toFixed(1))}</b><span>♥ ${esc(compact(r.like_count))}</span><span>↻ ${esc(compact(r.repost_count))}</span><span>↩ ${esc(compact(r.reply_count))}</span></div><span class="trend-note">Discovered ${esc(age(r.created_at))} · public X engagement</span><div class="trend-actions"><button class="trend-add" type="button" data-add="${esc(r.tweet_id)}">Add to Betslip</button><a class="trend-x" href="${esc(r.tweet_url)}" target="_blank" rel="noopener noreferrer">View on X ↗</a></div></article>`;}
  function render(){renderControls();const all=rows.filter(upcoming),scope=sorted(),shown=scope.slice(0,visible);q('#trendCount').textContent=String(all.length);q('#trendStatus').textContent=all.length?`${scope.length} upcoming bet${scope.length===1?'':'s'} · refreshed hourly · started/live slips excluded`:'No analyzed upcoming trends are available right now.';q('#trendGrid').innerHTML=shown.length?shown.map(card).join(''):'<div class="trend-empty">No upcoming analyzed betslips match this filter right now.</div>';const more=q('#trendLoadMore');more.hidden=shown.length>=scope.length;more.textContent=`Show more trending bets (${scope.length-shown.length} remaining)`;}
  async function load(){if(loading)return;loading=true;q('#trendRefresh').disabled=true;q('#trendStatus').textContent='Refreshing public X trends…';const now=encodeURIComponent(new Date().toISOString()),fields='tweet_id,tweet_url,author_username,author_name,text,sport,media_url,created_at,like_count,repost_count,reply_count,quote_count,bookmark_count,impression_count,attention_score,refreshed_at,event_start_at,event_label,is_pregame_confirmed,bet_probability_pct,probability_kind,analysis_summary,builder_ready';try{const res=await fetch(`${SUPABASE_URL}/rest/v1/x_trending_betslips?is_active=eq.true&is_pregame_confirmed=eq.true&builder_ready=eq.true&event_start_at=gt.${now}&select=${fields}&order=attention_score.desc,created_at.desc&limit=60`,{headers:{apikey:SUPABASE_KEY}});if(!res.ok)throw new Error(`Feed unavailable (${res.status})`);rows=await res.json();visible=18;render();}catch(e){rows=[];q('#trendGrid').innerHTML=`<div class="trend-empty trend-danger">${esc(e.message||'Could not load trending bets.')}</div>`;q('#trendStatus').textContent='Trending feed unavailable.';}finally{loading=false;q('#trendRefresh').disabled=false;}}
  async function add(id,button){button.disabled=true;button.textContent='Opening Builder…';try{const res=await fetch('/api/trending-build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tweet_id:id})}),p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||`Could not add bet (${res.status})`);location.assign(p.builderUrl);}catch(e){button.disabled=false;button.textContent='Add to Betslip';alert(e.message||'Could not add this bet to Builder.');}}
  function wire(){document.addEventListener('click',e=>{const s=e.target.closest('[data-sport]');if(s){sport=s.dataset.sport||'ALL';visible=18;render();return;}const so=e.target.closest('[data-sort]');if(so){sort=so.dataset.sort||'attention';visible=18;render();return;}const addBtn=e.target.closest('[data-add]');if(addBtn){add(addBtn.dataset.add,addBtn);}});q('#trendLoadMore').addEventListener('click',()=>{visible+=18;render();});q('#trendRefresh').addEventListener('click',load);}
  function init(){wire();renderControls();load();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();