(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  let byBuilder=new Map();
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function normUrl(value){try{return new URL(String(value||''),location.origin).href;}catch{return String(value||'');}}
  async function get(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY}});if(!r.ok)return[];const p=await r.json();return Array.isArray(p)?p:[];}
  function style(){if(document.getElementById('ppGrowthTrendStyle'))return;const s=document.createElement('style');s.id='ppGrowthTrendStyle';s.textContent='.pp-founder-chip{display:inline-flex;align-items:center;padding:5px 8px;margin-left:7px;border:1px solid rgba(73,220,206,.32);border-radius:999px;background:rgba(73,220,206,.09);color:#76e6dc;font-size:10px;font-weight:900;letter-spacing:.055em;white-space:nowrap}.pp-contributor-section{margin:34px 0;padding:26px;border:1px solid rgba(78,215,203,.17);border-radius:24px;background:linear-gradient(145deg,rgba(8,36,49,.92),rgba(6,27,40,.92))}.pp-contributor-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;margin-bottom:18px}.pp-contributor-head h2{margin:5px 0 7px;font:700 28px/1.05 Space Grotesk,Inter,sans-serif}.pp-contributor-head p{margin:0;color:#91b1b4;max-width:700px;line-height:1.55}.pp-contributor-note{flex:none;padding:7px 10px;border-radius:999px;border:1px solid rgba(73,220,206,.24);color:#75dfd6;font-size:10px;font-weight:900;letter-spacing:.08em}.pp-contributor-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.pp-contributor-card{display:grid;gap:10px;padding:17px;border:1px solid rgba(255,255,255,.08);border-radius:17px;background:rgba(255,255,255,.025);text-decoration:none;color:inherit}.pp-contributor-card:hover{border-color:rgba(73,220,206,.28)}.pp-contributor-top{display:flex;gap:8px;align-items:center;justify-content:space-between}.pp-contributor-name{font-weight:900;color:#f3fffd}.pp-contributor-founder{color:#66ddd2;font-size:9px;font-weight:900;letter-spacing:.07em}.pp-contributor-record{font:700 26px/1 Space Grotesk,Inter,sans-serif;color:#fff}.pp-contributor-record small{font:700 10px/1 Inter,sans-serif;color:#78999d;letter-spacing:.08em;margin-left:5px}.pp-contributor-metrics{display:flex;flex-wrap:wrap;gap:7px;color:#8caaad;font-size:10px}.pp-contributor-metrics span{padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.035)}.pp-contributor-empty{grid-column:1/-1;padding:22px;border:1px dashed rgba(255,255,255,.12);border-radius:15px;color:#87a9ac;text-align:center}@media(max-width:900px){.pp-contributor-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.pp-contributor-section{padding:19px 15px}.pp-contributor-head{align-items:flex-start;flex-direction:column}.pp-contributor-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function decorate(){document.querySelectorAll('#trendGrid .trend-card').forEach(card=>{if(card.dataset.ppFounderDecorated)return;const badge=card.querySelector('.verified-badge');if(!badge||!String(badge.textContent||'').includes('COMMUNITY'))return;const build=card.querySelector('.trend-add[href]');if(!build)return;const meta=byBuilder.get(normUrl(build.getAttribute('href')));if(!meta?.founding_number){card.dataset.ppFounderDecorated='1';return;}const chip=document.createElement('span');chip.className='pp-founder-chip';chip.textContent=`FOUNDING #${String(meta.founding_number).padStart(3,'0')}`;badge.insertAdjacentElement('afterend',chip);card.dataset.ppFounderDecorated='1';});}
  function renderLeaderboard(rows){const grid=document.getElementById('communityLeaderboardGrid');if(!grid)return;if(!rows.length){grid.innerHTML='<div class="pp-contributor-empty">Verified contributor records will appear here after Community members submit and their games settle.</div>';return;}grid.innerHTML=rows.slice(0,12).map(row=>{const w=Number(row.win_count)||0,l=Number(row.loss_count)||0,p=Number(row.push_count)||0,settled=Number(row.settled_submission_count)||0,verified=Number(row.verified_submission_count)||0,invites=Number(row.invite_count)||0,rate=row.win_rate_pct==null?null:Number(row.win_rate_pct),name=row.x_username?`@${String(row.x_username).replace(/^@/,'')}`:(row.author_name||'ParlayPing member'),record=w+l?`${w}-${l}`:'Awaiting results',href=row.latest_builder_url||'/submit';return `<a class="pp-contributor-card" href="${esc(href)}"><div class="pp-contributor-top"><span class="pp-contributor-name">${esc(name)}</span>${row.founding_number?`<span class="pp-contributor-founder">FOUNDING #${String(row.founding_number).padStart(3,'0')}</span>`:''}</div><div class="pp-contributor-record">${esc(record)}${w+l?'<small>W-L</small>':''}</div><div class="pp-contributor-metrics"><span>${verified} verified</span><span>${settled} settled</span>${p?`<span>${p} push</span>`:''}${rate!=null?`<span>${rate}% W-L</span>`:''}<span>${invites} invite${invites===1?'':'s'}</span></div></a>`;}).join('');}
  async function load(){const [posts,badges,leaderboard]=await Promise.all([get('community_parlays?is_active=eq.true&verified_pregame=eq.true&select=user_id,builder_url&limit=250'),get('member_badges?founding_number=not.is.null&select=user_id,founding_number,referral_code&limit=100'),get('community_leaderboard?select=user_id,referral_code,founding_number,invite_count,verified_submission_count,settled_submission_count,win_count,loss_count,push_count,void_count,win_rate_pct,author_name,x_username,latest_builder_url,latest_submission_at&order=win_count.desc,verified_submission_count.desc&limit=12')]);const badgeMap=new Map(badges.map(row=>[row.user_id,row]));byBuilder=new Map(posts.map(row=>[normUrl(row.builder_url),badgeMap.get(row.user_id)]).filter(([,value])=>value));renderLeaderboard(leaderboard);decorate();}
  function init(){style();load();const grid=document.getElementById('trendGrid');if(grid&&typeof MutationObserver==='function')new MutationObserver(decorate).observe(grid,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();