(()=>{
  const SUPABASE_URL='https://avwqjgiitxqphvmitolw.supabase.co';
  const SUPABASE_KEY='sb_publishable_7mYXjjkRrQq3iRig7UYHNQ_b6EZZiJA';
  const SPORTS=['ALL','NFL','NCAAF','NBA','WNBA','NCAAB','MLB','NHL'];
  const SORTS=[['attention','High attention'],['probability','Probability'],['social','Likes + reposts']];
  const PROP_FILTERS=[['ALL','All props'],['TD','Touchdowns'],['REC_YDS','Receiving yards'],['RECEPTIONS','Receptions'],['RUSH_YDS','Rushing yards'],['PASSING','Passing'],['OTHER','Other props']];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const q=s=>document.querySelector(s);
  let rows=[],players=[],selections=[],sport='ALL',sort='attention',visible=24,pulseTab='players',propFilter='ALL',loading=false;

  function compact(v){const n=Number(v)||0;if(n>=1e6)return`${(n/1e6).toFixed(n>=1e7?0:1)}M`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e4?0:1)}K`;return String(Math.round(n));}
  function pctText(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n))return null;if(n>0&&n<.1)return'<0.1%';return`${n.toFixed(n%1?1:0)}%`;}
  function formatStart(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'upcoming';return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(t));}
  function age(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'recently';const m=Math.max(0,Math.floor((Date.now()-t)/60000));return m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`;}
  function upcoming(r){const t=Date.parse(r?.event_start_at||'');return Number.isFinite(t)&&t>Date.now();}
  function socialScore(r){return (Number(r.like_count)||0)+(Number(r.repost_count)||0);}
  function probability(r){const v=r?.bet_probability_pct;if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
  function probabilitySource(r){return String(r?.probability_kind||'').startsWith('market-implied')?'Market-implied':'ParlayPing model';}
  function barWidth(v){const n=Number(v);if(!Number.isFinite(n)||n<=0)return 0;return Math.max(.8,Math.min(100,n));}

  function sorted(){let out=rows.filter(upcoming).filter(r=>sport==='ALL'||String(r.sport||'').toUpperCase()===sport);out=[...out];if(sort==='probability')out.sort((a,b)=>(probability(b)??-1)-(probability(a)??-1)||Number(b.attention_score||0)-Number(a.attention_score||0));else if(sort==='social')out.sort((a,b)=>socialScore(b)-socialScore(a)||Number(b.attention_score||0)-Number(a.attention_score||0));else out.sort((a,b)=>Number(b.attention_score||0)-Number(a.attention_score||0)||socialScore(b)-socialScore(a));return out;}

  function propGroup(r){const m=String(r?.market||'').toLowerCase(),d=String(r?.display_market||'').toLowerCase();if(/\batd\b|touchdown|td scorer|first td/.test(`${m} ${d}`))return'TD';if(/recyds|receiving/.test(`${m} ${d}`))return'REC_YDS';if(/receptions|\brec\b/.test(`${m} ${d}`))return'RECEPTIONS';if(/rushyds|rushing/.test(`${m} ${d}`))return'RUSH_YDS';if(/passyds|passing|pass td|completions|attempts|interceptions/.test(`${m} ${d}`))return'PASSING';return'OTHER';}
  function propRank(a,b){return Number(b.slip_count||0)-Number(a.slip_count||0)||Number(b.attention_score||0)-Number(a.attention_score||0)||socialScore(b)-socialScore(a);}
  function diversifiedProps(source,limit=12){const groups=['TD','REC_YDS','RECEPTIONS','RUSH_YDS','PASSING','OTHER'],buckets=new Map(groups.map(g=>[g,[]]));source.forEach(r=>buckets.get(propGroup(r))?.push(r));buckets.forEach(list=>list.sort(propRank));const out=[],seen=new Set();for(let round=0;round<3&&out.length<limit;round++)for(const g of groups){const item=buckets.get(g)?.[round];if(item&&!seen.has(item.selection_key)){seen.add(item.selection_key);out.push(item);if(out.length>=limit)break;}}if(out.length<limit){for(const item of [...source].sort(propRank)){if(seen.has(item.selection_key))continue;seen.add(item.selection_key);out.push(item);if(out.length>=limit)break;}}return out;}

  function renderControls(){q('#trendSportFilters').innerHTML=SPORTS.map(s=>`<button class="trend-pill${sport===s?' active':''}" type="button" data-sport="${s}">${s==='ALL'?'All':s}</button>`).join('');q('#trendSortFilters').innerHTML=SORTS.map(([key,label])=>`<button class="trend-pill${sort===key?' active':''}" type="button" data-sort="${key}">${label}</button>`).join('');}
  function renderPropFilters(){const box=q('#pulseMarketFilters');if(!box)return;box.hidden=pulseTab!=='selections';box.innerHTML=PROP_FILTERS.map(([key,label])=>`<button class="pulse-market${propFilter===key?' active':''}" type="button" data-prop-filter="${key}">${label}</button>`).join('');}
  function pulseMetric(row){return `${Number(row.slip_count||0)} verified slip${Number(row.slip_count||0)===1?'':'s'}`;}
  function pulseCard(row,type){const prob=pctText(row.avg_leg_probability_pct),social=`♥ ${compact(row.like_count)} · ↻ ${compact(row.repost_count)}`;if(type==='players')return `<article class="pulse-card"><div class="pulse-card-top"><span>NFL</span><b>${esc(pulseMetric(row))}</b></div><strong>${esc(row.player||'Unknown')}</strong><p>${prob?`Avg modeled leg probability ${esc(prob)} · `:''}${esc(social)}</p><div class="pulse-strength"><span style="width:${Math.min(100,Math.max(5,Number(row.slip_count||0)*18))}%"></span></div></article>`;return `<article class="pulse-card"><div class="pulse-card-top"><span>${esc(PROP_FILTERS.find(([k])=>k===propGroup(row))?.[1]||'NFL prop')}</span><b>${esc(pulseMetric(row))}</b></div><strong>${esc(row.player||'Unknown')}</strong><p>${esc(row.display_market||row.market||'Selection')}${prob?` · ${esc(prob)}`:''}</p><div class="pulse-card-foot"><span>${esc(social)}</span>${row.sample_tweet_id?`<a href="/verified/${esc(row.sample_tweet_id)}">Verified example →</a>`:''}</div></article>`;}
  function renderPulse(){document.querySelectorAll('[data-pulse-tab]').forEach(b=>b.classList.toggle('active',b.dataset.pulseTab===pulseTab));renderPropFilters();let source;if(pulseTab==='players'){source=[...players].sort((a,b)=>Number(b.slip_count||0)-Number(a.slip_count||0)||Number(b.attention_score||0)-Number(a.attention_score||0)).slice(0,12);}else{const all=[...selections].filter(r=>String(r.sport||'').toUpperCase()==='NFL');source=propFilter==='ALL'?diversifiedProps(all,12):all.filter(r=>propGroup(r)===propFilter).sort(propRank).slice(0,12);}const grid=q('#pulseGrid');grid.innerHTML=source.length?source.map(r=>pulseCard(r,pulseTab)).join(''):'<div class="pulse-loading">No verified upcoming NFL props match this view yet.</div>';}

  function card(r){const p=probability(r),source=probabilitySource(r),probText=p!=null?`${source} ${pctText(p)}`:'Probability unavailable',bar=p!=null?`<div class="trend-probability"><div class="trend-probability-head"><span>${esc(source)} probability</span><b>${esc(pctText(p))}</b></div><div class="trend-probbar"><span style="width:${barWidth(p)}%"></span></div></div>`:'',author=r.author_username?`@${r.author_username}`:(r.author_name||'X user'),media=r.media_url?`<a class="trend-media" href="/verified/${esc(r.tweet_id)}"><img src="${esc(r.media_url)}" alt="Verified public betslip from ${esc(author)}" loading="lazy" decoding="async"></a>`:'';return `<article class="trend-card"><div class="trend-verify-row"><a class="verified-badge" href="/verified/${esc(r.tweet_id)}">✓ VERIFIED BETSLIP</a><span>${esc(r.sport||'SPORTS')} · ${esc(formatStart(r.event_start_at))}</span></div>${media}<div class="trend-top"><strong class="trend-author">${esc(author)}</strong><span class="trend-prob">${esc(probText)}</span></div><p class="trend-text">${esc(r.original_text||'Public betslip on X')}</p><p class="trend-analysis">${esc(r.analysis_summary||'Verified pregame by ParlayPing.')}</p>${bar}<div class="trend-meta"><b>Attention ${esc(Number(r.attention_score||0).toFixed(1))}</b><span>♥ ${esc(compact(r.like_count))}</span><span>↻ ${esc(compact(r.repost_count))}</span><span>↩ ${esc(compact(r.reply_count))}</span></div><span class="trend-note">Verified ${esc(age(r.last_verified_at||r.first_verified_at))} · public X source</span><div class="trend-actions"><button class="trend-add" type="button" data-add="${esc(r.tweet_id)}">Add to Betslip</button><a class="trend-x" href="/verified/${esc(r.tweet_id)}">Verification</a><a class="trend-x" href="${esc(r.tweet_url)}" target="_blank" rel="noopener noreferrer">X ↗</a></div></article>`;}
  function render(){renderControls();renderPulse();const all=rows.filter(upcoming),scope=sorted(),shown=scope.slice(0,visible);q('#trendCount').textContent=String(all.length);q('#trendStatus').textContent=all.length?`${scope.length} verified upcoming bet${scope.length===1?'':'s'} · started/live slips excluded`:'No verified upcoming trends are available right now.';q('#trendGrid').innerHTML=shown.length?shown.map(card).join(''):'<div class="trend-empty">No verified upcoming betslips match this filter right now.</div>';const more=q('#trendLoadMore');more.hidden=shown.length>=scope.length;more.textContent=`Show more trending bets (${scope.length-shown.length} remaining)`;}

  async function get(path){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY}});if(!res.ok)throw new Error(`Feed unavailable (${res.status})`);return res.json();}
  async function load(){if(loading)return;loading=true;q('#trendRefresh').disabled=true;q('#trendStatus').textContent='Refreshing verified X trends…';const now=encodeURIComponent(new Date().toISOString());try{const [feed,p,s]=await Promise.all([get(`x_verified_betslips?event_start_at=gt.${now}&select=tweet_id,tweet_url,author_username,author_name,sport,original_text,media_url,source_created_at,event_start_at,event_label,first_verified_at,last_verified_at,bet_probability_pct,probability_kind,analysis_summary,like_count,repost_count,reply_count,attention_score&order=attention_score.desc,last_verified_at.desc&limit=150`),get('x_trending_players?sport=eq.NFL&select=*&order=slip_count.desc,attention_score.desc&limit=100'),get('x_trending_selections?sport=eq.NFL&select=*&order=slip_count.desc,attention_score.desc&limit=200')]);rows=Array.isArray(feed)?feed:[];players=Array.isArray(p)?p:[];selections=Array.isArray(s)?s:[];visible=24;render();}catch(e){rows=[];players=[];selections=[];q('#trendGrid').innerHTML=`<div class="trend-empty trend-danger">${esc(e.message||'Could not load trending bets.')}</div>`;q('#trendStatus').textContent='Trending feed unavailable.';renderPulse();}finally{loading=false;q('#trendRefresh').disabled=false;}}
  async function add(id,button){button.disabled=true;button.textContent='Opening Builder…';try{const res=await fetch('/api/trending-build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tweet_id:id})}),p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(p?.error||`Could not add bet (${res.status})`);location.assign(p.builderUrl);}catch(e){button.disabled=false;button.textContent='Add to Betslip';alert(e.message||'Could not add this bet to Builder.');}}
  function wire(){document.addEventListener('click',e=>{const pt=e.target.closest('[data-pulse-tab]');if(pt){pulseTab=pt.dataset.pulseTab||'players';propFilter='ALL';renderPulse();return;}const pf=e.target.closest('[data-prop-filter]');if(pf){propFilter=pf.dataset.propFilter||'ALL';renderPulse();return;}const s=e.target.closest('[data-sport]');if(s){sport=s.dataset.sport||'ALL';visible=24;render();return;}const so=e.target.closest('[data-sort]');if(so){sort=so.dataset.sort||'attention';visible=24;render();return;}const addBtn=e.target.closest('[data-add]');if(addBtn){add(addBtn.dataset.add,addBtn);}});q('#trendLoadMore').addEventListener('click',()=>{visible+=24;render();});q('#trendRefresh').addEventListener('click',load);}
  function init(){wire();renderControls();load();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();