create table if not exists public.sports_insights (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  sport text not null,
  category text not null default 'Team / player update',
  headline text not null,
  summary text,
  entity_name text,
  entity_type text,
  source_name text,
  source_url text not null,
  source_published_at timestamptz,
  score numeric not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  discovered_at timestamptz not null default now(),
  refreshed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '48 hours'),
  is_active boolean not null default true
);

create index if not exists sports_insights_active_score_idx on public.sports_insights (is_active, score desc, source_published_at desc);
create index if not exists sports_insights_sport_idx on public.sports_insights (sport, is_active, score desc);

alter table public.sports_insights enable row level security;
drop policy if exists "sports insights are publicly readable" on public.sports_insights;
create policy "sports insights are publicly readable" on public.sports_insights for select to anon, authenticated using (is_active = true and expires_at > now());
grant select on public.sports_insights to anon, authenticated;

create table if not exists public.x_trending_betslips (
  tweet_id text primary key,
  tweet_url text not null,
  author_id text,
  author_username text,
  author_name text,
  text text not null,
  sport text not null default 'SPORTS',
  media_url text,
  created_at timestamptz,
  like_count integer not null default 0,
  repost_count integer not null default 0,
  reply_count integer not null default 0,
  quote_count integer not null default 0,
  bookmark_count integer not null default 0,
  impression_count bigint not null default 0,
  attention_score numeric not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  discovered_at timestamptz not null default now(),
  refreshed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours'),
  is_active boolean not null default true
);

create index if not exists x_trending_betslips_active_score_idx on public.x_trending_betslips (is_active, attention_score desc, created_at desc);
create index if not exists x_trending_betslips_sport_idx on public.x_trending_betslips (sport, is_active, attention_score desc);

alter table public.x_trending_betslips enable row level security;
drop policy if exists "x trending betslips are publicly readable" on public.x_trending_betslips;
create policy "x trending betslips are publicly readable" on public.x_trending_betslips for select to anon, authenticated using (is_active = true and expires_at > now());
grant select on public.x_trending_betslips to anon, authenticated;

create or replace function public.parlayping_publish_discovery(
  p_scheduler_secret text,
  p_insights jsonb default '[]'::jsonb,
  p_trending jsonb default '[]'::jsonb,
  p_insights_ok boolean default true,
  p_trending_ok boolean default true,
  p_run_at timestamptz default now()
) returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_expected text;
  v_item jsonb;
  v_insights integer := 0;
  v_trending integer := 0;
begin
  v_expected := public.parlayping_get_scheduler_secret();
  if p_scheduler_secret is null
     or encode(extensions.digest(p_scheduler_secret, 'sha256'), 'hex') <> encode(extensions.digest(v_expected, 'sha256'), 'hex') then
    raise exception 'Unauthorized discovery publish.';
  end if;

  if p_insights_ok and jsonb_typeof(p_insights) = 'array' and jsonb_array_length(p_insights) > 0 then
    update public.sports_insights set is_active = false where is_active = true;
    for v_item in select value from jsonb_array_elements(p_insights) limit 50 loop
      insert into public.sports_insights(
        source_key, sport, category, headline, summary, entity_name, entity_type,
        source_name, source_url, source_published_at, score, metadata,
        discovered_at, refreshed_at, expires_at, is_active
      ) values (
        left(v_item->>'source_key', 500),
        left(coalesce(nullif(v_item->>'sport',''), 'SPORTS'), 32),
        left(coalesce(nullif(v_item->>'category',''), 'Team / player update'), 80),
        left(v_item->>'headline', 500),
        left(v_item->>'summary', 1000),
        left(v_item->>'entity_name', 160),
        left(v_item->>'entity_type', 40),
        left(v_item->>'source_name', 160),
        left(v_item->>'source_url', 2000),
        nullif(v_item->>'source_published_at','')::timestamptz,
        coalesce(nullif(v_item->>'score','')::numeric, 0),
        coalesce(v_item->'metadata', '{}'::jsonb),
        p_run_at, p_run_at, p_run_at + interval '48 hours', true
      )
      on conflict (source_key) do update set
        sport = excluded.sport, category = excluded.category, headline = excluded.headline,
        summary = excluded.summary, entity_name = excluded.entity_name, entity_type = excluded.entity_type,
        source_name = excluded.source_name, source_url = excluded.source_url,
        source_published_at = excluded.source_published_at, score = excluded.score,
        metadata = excluded.metadata, refreshed_at = excluded.refreshed_at,
        expires_at = excluded.expires_at, is_active = true;
      v_insights := v_insights + 1;
    end loop;
  end if;

  if p_trending_ok and jsonb_typeof(p_trending) = 'array' and jsonb_array_length(p_trending) > 0 then
    update public.x_trending_betslips set is_active = false where is_active = true;
    for v_item in select value from jsonb_array_elements(p_trending) limit 50 loop
      insert into public.x_trending_betslips(
        tweet_id, tweet_url, author_id, author_username, author_name, text, sport,
        media_url, created_at, like_count, repost_count, reply_count, quote_count,
        bookmark_count, impression_count, attention_score, metadata,
        discovered_at, refreshed_at, expires_at, is_active
      ) values (
        left(v_item->>'tweet_id', 80), left(v_item->>'tweet_url', 2000),
        left(v_item->>'author_id', 80), left(v_item->>'author_username', 100),
        left(v_item->>'author_name', 160), left(v_item->>'text', 2000),
        left(coalesce(nullif(v_item->>'sport',''), 'SPORTS'), 32), left(v_item->>'media_url', 2000),
        nullif(v_item->>'created_at','')::timestamptz,
        coalesce(nullif(v_item->>'like_count','')::integer, 0),
        coalesce(nullif(v_item->>'repost_count','')::integer, 0),
        coalesce(nullif(v_item->>'reply_count','')::integer, 0),
        coalesce(nullif(v_item->>'quote_count','')::integer, 0),
        coalesce(nullif(v_item->>'bookmark_count','')::integer, 0),
        coalesce(nullif(v_item->>'impression_count','')::bigint, 0),
        coalesce(nullif(v_item->>'attention_score','')::numeric, 0),
        coalesce(v_item->'metadata', '{}'::jsonb),
        p_run_at, p_run_at, p_run_at + interval '12 hours', true
      )
      on conflict (tweet_id) do update set
        tweet_url = excluded.tweet_url, author_id = excluded.author_id,
        author_username = excluded.author_username, author_name = excluded.author_name,
        text = excluded.text, sport = excluded.sport, media_url = excluded.media_url,
        created_at = excluded.created_at, like_count = excluded.like_count,
        repost_count = excluded.repost_count, reply_count = excluded.reply_count,
        quote_count = excluded.quote_count, bookmark_count = excluded.bookmark_count,
        impression_count = excluded.impression_count, attention_score = excluded.attention_score,
        metadata = excluded.metadata, refreshed_at = excluded.refreshed_at,
        expires_at = excluded.expires_at, is_active = true;
      v_trending := v_trending + 1;
    end loop;
  end if;

  delete from public.sports_insights where expires_at < p_run_at - interval '7 days';
  delete from public.x_trending_betslips where expires_at < p_run_at - interval '7 days';

  return jsonb_build_object('ok', true, 'insightsPublished', v_insights, 'trendingPublished', v_trending,
    'insightsAccepted', p_insights_ok, 'trendingAccepted', p_trending_ok, 'runAt', p_run_at);
end;
$$;

revoke all on function public.parlayping_publish_discovery(text,jsonb,jsonb,boolean,boolean,timestamptz) from public;
grant execute on function public.parlayping_publish_discovery(text,jsonb,jsonb,boolean,boolean,timestamptz) to anon, authenticated;
