const crypto = require('crypto');
const { parseSlip } = require('./lib/slip-parser');
const { analyzeMultiSport } = require('./lib/sport-router');
const { applyCorrelationSafety, replyReadiness, buildPublicReply } = require('./lib/analysis-safety');

const X_API = 'https://api.x.com/2';
const X_USERNAME = process.env.X_USERNAME || 'ParlayPing';
function pct(value){return encodeURIComponent(String(value)).replace(/!/g,'%21').replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29').replace(/\*/g,'%2A');}
function oauthCredentials(){const apiKey=process.env.X_API_KEY,apiSecret=process.env.X_API_SECRET,accessToken=process.env.X_ACCESS_TOKEN,accessTokenSecret=process.env.X_ACCESS_TOKEN_SECRET;if(!apiKey||!apiSecret||!accessToken||!accessTokenSecret)throw new Error('X OAuth 1.0a credentials are incomplete. Configure X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, and X_ACCESS_TOKEN_SECRET.');return{apiKey,apiSecret,accessToken,accessTokenSecret};}
function oauthHeader(method,rawUrl){const{apiKey,apiSecret,accessToken,accessTokenSecret}=oauthCredentials();const url=new URL(rawUrl);const oauth={oauth_consumer_key:apiKey,oauth_nonce:crypto.randomBytes(18).toString('hex'),oauth_signature_method:'HMAC-SHA1',oauth_timestamp:String(Math.floor(Date.now()/1000)),oauth_token:accessToken,oauth_version:'1.0'};const pairs=[];for(const[key,value]of url.searchParams.entries())pairs.push([pct(key),pct(value)]);for(const[key,value]of Object.entries(oauth))pairs.push([pct(key),pct(value)]);pairs.sort((a,b)=>a[0]===b[0]?a[1].localeCompare(b[1]):a[0].localeCompare(b[0]));const parameterString=pairs.map(([k,v])=>`${k}=${v}`).join('&');const baseUrl=`${url.protocol}//${url.host}${url.pathname}`;const signatureBase=[method.toUpperCase(),pct(baseUrl),pct(parameterString)].join('&');const signingKey=`${pct(apiSecret)}&${pct(accessTokenSecret)}`;oauth.oauth_signature=crypto.createHmac('sha1',signingKey).update(signatureBase).digest('base64');return `OAuth ${Object.keys(oauth).sort().map(key=>`${pct(key)}="${pct(oauth[key])}"`).join(', ')}`;}
async function xRequest(method,path,body){const url=`${X_API}${path}`;const headers={authorization:oauthHeader(method,url)};const options={method,headers};if(body!==undefined){headers['content-type']='application/json';options.body=JSON.stringify(body);}const response=await fetch(url,options);const text=await response.text();let payload={};try{payload=text?JSON.parse(text):{};}catch(_){payload={detail:text};}if(!response.ok)throw new Error(payload?.detail||payload?.title||payload?.errors?.[0]?.message||`X API ${method} failed (${response.status})`);return payload;}
const xGet=path=>xRequest('GET',path);const xPost=(path,body)=>xRequest('POST',path,body);
async function resolveBotUserId(){if(process.env.X_USER_ID)return String(process.env.X_USER_ID);const me=await xGet('/users/me?user.fields=id,username,name');const id=me?.data?.id;if(!id)throw new Error('Unable to resolve the authenticated X user with /users/me.');if(me?.data?.username&&String(me.data.username).toLowerCase()!==X_USERNAME.toLowerCase())throw new Error(`X credentials are authenticated as @${me.data.username}, not @${X_USERNAME}.`);return String(id);}
function replyTarget(tweet){return (tweet?.referenced_tweets||[]).find(r=>r.type==='replied_to')?.id||(tweet?.referenced_tweets||[]).find(r=>r.type==='quoted')?.id||null;}
function collectMediaUrls(tweet,mediaByKey){const out=[];for(const key of tweet?.attachments?.media_keys||[]){const media=mediaByKey.get(String(key));const url=media?.url||media?.preview_image_url;if(url)out.push(url);}return out;}
async function hydrateMissingParents(mentions,includesTweets,mediaByKey){const missing=[...new Set(mentions.map(replyTarget).filter(Boolean).map(String).filter(id=>!includesTweets.has(id)))];if(!missing.length)return;const q=new URLSearchParams({ids:missing.join(','),'tweet.fields':'author_id,attachments,created_at,conversation_id,possibly_sensitive,referenced_tweets,text',expansions:'attachments.media_keys','media.fields':'media_key,type,url,preview_image_url'});const fetched=await xGet(`/tweets?${q}`);for(const tweet of fetched.data||[])includesTweets.set(String(tweet.id),tweet);for(const media of fetched.includes?.media||[])mediaByKey.set(String(media.media_key),media);}
async function getContext(userId){const q=new URLSearchParams({max_results:'20','tweet.fields':'author_id,attachments,created_at,conversation_id,possibly_sensitive,referenced_tweets,text',expansions:'author_id,attachments.media_keys,referenced_tweets.id,referenced_tweets.id.attachments.media_keys','media.fields':'media_key,type,url,preview_image_url','user.fields':'username,name'});const mentions=await xGet(`/users/${userId}/mentions?${q}`);const own=await xGet(`/users/${userId}/tweets?max_results=100&tweet.fields=referenced_tweets,created_at`);const replied=new Set();for(const tweet of own.data||[])for(const ref of tweet.referenced_tweets||[])if(ref.type==='replied_to')replied.add(String(ref.id));return{mentions,replied};}

async function processMentions({dryRun}){
  const userId=await resolveBotUserId();const{mentions,replied}=await getContext(userId);const includesTweets=new Map((mentions.includes?.tweets||[]).map(t=>[String(t.id),t]));const mediaByKey=new Map((mentions.includes?.media||[]).map(m=>[String(m.media_key),m]));const actionableMentions=(mentions.data||[]).filter(mention=>!replied.has(String(mention.id))&&!mention.possibly_sensitive&&!/\b(stop|unsubscribe|opt\s*out)\b/i.test(mention.text||'')&&Boolean(replyTarget(mention)));await hydrateMissingParents(actionableMentions,includesTweets,mediaByKey);
  const candidates=[];
  for(const mention of [...actionableMentions].reverse()){
    const parentId=replyTarget(mention),parent=includesTweets.get(String(parentId));if(!parent){candidates.push({mentionId:mention.id,parentId,status:'unavailable-parent'});continue;}
    const mediaUrls=collectMediaUrls(parent,mediaByKey),parsed=await parseSlip({text:parent.text||'',mediaUrls});if(!parsed.legs.length){candidates.push({mentionId:mention.id,parentId,status:'unparsed',parser:parsed.method,mediaCount:mediaUrls.length});continue;}
    const raw=await analyzeMultiSport(parsed.legs,{baseUrl:process.env.PUBLIC_BASE_URL||'https://parlayping.net',referenceTime:parent.created_at||mention.created_at||null});const analysis=applyCorrelationSafety(raw),readiness=replyReadiness(analysis);const row={mentionId:mention.id,parentId,status:readiness.ready?'ready':'needs-match',parser:parsed.method,sports:parsed.sports||[],mediaCount:mediaUrls.length,counts:analysis.counts,readiness,unresolvedLegs:(analysis.results||[]).filter(r=>r?.status==='UNRESOLVED').map(r=>({sport:r.sport||null,player:r.player||null,team:r.team||null,market:r.market||null,side:r.side||null,line:r.line??null,originalText:r.originalText||null,reason:r.resolutionReason||'unresolved-leg'})),correlation:analysis.correlation,combinedTailProbability:analysis.combinedTailProbability,combinedTailProbabilityMethod:analysis.combinedTailProbabilityMethod,tailUrl:analysis.tailUrl,replyText:readiness.ready?buildPublicReply(analysis,{maxLegs:3}):null};
    if(!dryRun&&readiness.ready&&row.replyText){const posted=await xPost('/tweets',{text:row.replyText,reply:{in_reply_to_tweet_id:String(mention.id)}});row.status='replied';row.replyId=posted?.data?.id||null;}
    candidates.push(row);
  }
  return candidates;
}

module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');try{const workerSecret=process.env.X_WORKER_SECRET;const supplied=req.headers['x-parlayping-secret']||req.query?.secret;if(workerSecret&&supplied!==workerSecret)return res.status(401).json({ok:false,error:'Unauthorized.'});const approved=String(process.env.X_AI_REPLY_APPROVED||'').toLowerCase()==='true';const enabled=String(process.env.X_AUTOREPLY_ENABLED||'').toLowerCase()==='true';const dryRun=!(approved&&enabled);const candidates=await processMentions({dryRun});return res.status(200).json({ok:true,dryRun,username:X_USERNAME,auth:'oauth1-user-context',xApprovalRecorded:approved,autoReplyEnabled:enabled,analysisAdapters:['NFL','NCAAF','MLB'],processed:candidates.length,candidates});}catch(error){console.error('ParlayPing X worker',error);return res.status(500).json({ok:false,error:error?.message||'X worker failed.'});}};
